import pandas as pd
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

backlog_data = [
    # 1. Scope & Quantities
    {"ID": "SC-01", "Module": "Scope & Quantities", "Category_AR": "ÍæßãÉ ÇáäØÇŞ æÇáßãíÇÊ", "Feature_Name": "Unified Control Account (WBS/BOQ/CostCode/SOV)", "Feature_Name_AR": "ÍÓÇÈ ÇáÊÍßã ÇáãæÍÏ (Control Account Master)", "Description_AR": "ÑÈØ åÑãí ßÇãá Èíä ÚäÇÕÑ åíßá ÊÌÒÆÉ ÇáÚãá (WBS) æÈäæÏ ÇáãŞÇíÓÉ (BOQ) æÃßæÇÏ ÇáÊßÇáíİ (Cost Codes) æÈäæÏ ÌÏæá ÇáÏİÚÇÊ (SOV).", "PM_Value_AR": "ãäÚ ÇáÊÏÇÎá æÇÒÏæÇÌíÉ ÇáÕÑİ æÊÍÏíÏ ÇáãÓÄæáíÉ ÇáãÇáíÉ æÇáÊÔÛíáíÉ áßá ÈäÏ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Core Foundation)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate A / Foundation", "Technical_Evidence": "Migration 1-46, SqliteRepository, Checkpoint A1"},
    {"ID": "SC-02", "Module": "Scope & Quantities", "Category_AR": "ÍæßãÉ ÇáäØÇŞ æÇáßãíÇÊ", "Feature_Name": "Multi-State Quantity Ledger", "Feature_Name_AR": "ÏİÊÑ ÃÓÊÇĞ ÇáßãíÇÊ ÇáãÊÚÏÏ (Quantity Ledger)", "Description_AR": "ÊÊÈÚ ÏæÑÉ ÍíÇÉ ßãíÉ ÇáÈäÏ: ÃÕáíÉ ÇáÊÚÇŞÏ ? ÇáãÚÊãÏÉ ÈÚÏ ÇáÊÛííÑ ? ÇáãÎØØÉ ? ÇáãäİĞÉ İÍÕÇğ ? ÇáãŞÈæáÉ ÇÓÊÔÇÑíÇğ ? ÇáãÊÈŞíÉ.", "PM_Value_AR": "ÇáÊÍßã ÇáÕÇÑã İí ÇáßãíÇÊ æãäÚ ÇáÊÌÇæÒ ÇáÕÇãÊ ááÈäæÏ æÍãÇíÉ ÇáãŞÇæá ãä ÇáÕÑİ ÈÏæä ãÓÊäÏ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Governance)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate B / B1", "Technical_Evidence": "Checkpoint B1, QuantityLedger module"},
    {"ID": "SC-03", "Module": "Scope & Quantities", "Category_AR": "ÍæßãÉ ÇáäØÇŞ æÇáßãíÇÊ", "Feature_Name": "N-to-M BOQ Item ? Schedule Activities Allocation", "Feature_Name_AR": "ÚáÇŞÉ ÇáÊæÒíÚ ÇáãÊÚÏÏ (N-to-M BOQ ? Activities)", "Description_AR": "Êãßíä ÑÈØ ÈäÏ ÇáãŞÇíÓÉ ÇáæÇÍÏ ÈÚÏÉ ÃäÔØÉ ÌÏæáíÉ ãÚ äÓÈ ÇáÊæÒíÚ (%¡ ßãíÉ¡ ÊßáİÉ)¡ Ãæ ÇáäÔÇØ ÇáæÇÍÏ ÈÚÏÉ ÈäæÏ.", "PM_Value_AR": "ãÍÇßÇÉ ÇáæÇŞÚ ÇáÅäÔÇÆí ÈÏŞÉ æÊæÒíÚ ÊßÇáíİ æßãíÇÊ ÇáÈäÏ Úáì ãÑÇÍá ÊäİíĞå ÇáãÎÊáİÉ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Operational Reality)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate 1 / Feat 1", "Technical_Evidence": "Migration 47, boq_item_activities, 111 tests"},
    {"ID": "SC-04", "Module": "Scope & Quantities", "Category_AR": "ÍæßãÉ ÇáäØÇŞ æÇáßãíÇÊ", "Feature_Name": "Advanced Milestone Ladders & Rules of Credit", "Feature_Name_AR": "ÓáÇáã ÇáÅäÌÇÒ æŞæÇÚÏ ÇáÇÚÊãÇÏ (Rules of Credit)", "Description_AR": "ÊŞÓíã ÅäÌÇÒ ÇáÈäÏ/ÇáäÔÇØ áÎØæÇÊ ŞíÇÓíÉ ãÑÍáíÉ (ÊæÑíÏ 30%¡ ÊÑßíÈ 50%¡ ÇÎÊÈÇÑ 20%) ãÚ ÃæÒÇä ÍÓÇÈíÉ ãáÒãÉ.", "PM_Value_AR": "ÇÍÊÓÇÈ äÓÈÉ ÇáÅäÌÇÒ ÇáİÚáí æÇáãÓÊÍŞ ÈÏŞÉ æãäÚ ÇáãÈÇáÛÉ İí ÇáÅäÌÇÒ æÊÓåíá ÇÚÊãÇÏ ÇáãÓÊÎáÕÇÊ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Credibility)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate 1 / Feat 2", "Technical_Evidence": "Migration 48, milestone_ladder_templates, 112 tests"},
    {"ID": "SC-05", "Module": "Scope & Quantities", "Category_AR": "ÍæßãÉ ÇáäØÇŞ æÇáßãíÇÊ", "Feature_Name": "WIR Progress & Corrections Ledger", "Feature_Name_AR": "ÍæßãÉ ØáÈÇÊ İÍÕ ÇáÃÚãÇá æÇáÊÕÍíÍÇÊ (WIR)", "Description_AR": "ÑÈØ äÓÈ ÇáÅäÌÇÒ ÈØáÈÇÊ ÇÓÊáÇã ÇáÃÚãÇá (WIR) ÇáãÚÊãÏÉ ãÚ ÏİÊÑ ÊÓæíÇÊ áÊÕÍíÍ ßãíÇÊ ÇáÃÔÛÇá ÛíÑ ÇáãŞÈæáÉ.", "PM_Value_AR": "ãäÚ ÊÓÌíá ÊŞÏã İí ÇáãÔÑæÚ ÈÏæä ãæÇİŞÉ ÇáÇÓÊÔÇÑí ÇáÑÓãíÉ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí (Quality & Trust)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate B / B3", "Technical_Evidence": "WIR Ledger + Governance rules"},
    
    # 2. Schedule & CPM
    {"ID": "SCH-01", "Module": "Schedule & CPM", "Category_AR": "ÇáÌÏæáÉ æÇáãØÇáÈÇÊ ÇáÒãäíÉ", "Feature_Name": "Critical Path Method (CPM) Engine & Calendars", "Feature_Name_AR": "ãÍÑß ÇáãÓÇÑ ÇáÍÑÌ (CPM) æÇáÊŞÇæíã ÇáãÊŞÏãÉ", "Description_AR": "ÍÓÇÈ ÇáÊæÇÑíÎ ÇáãÈßÑÉ æÇáãÊÃÎÑÉ æÇáÓãÇÍíÇÊ (Total/Free Float) ãÚ ÏÚã ÊŞÇæíã ÇáÚãá æÇáÅÌÇÒÇÊ æÇáæÑÏíÇÊ.", "PM_Value_AR": "ÊÍÏíÏ ÇáÃäÔØÉ ÇáÍÑÌÉ ÈÏŞÉ æÊæŞÚ ÊÇÑíÎ ÇäÊåÇÁ ÇáãÔÑæÚ ÇáæÇŞÚí.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Core Planning)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate C / C1", "Technical_Evidence": "CPM Engine, Calendar aware, Checkpoint C1"},
    {"ID": "SCH-02", "Module": "Schedule & CPM", "Category_AR": "ÇáÌÏæáÉ æÇáãØÇáÈÇÊ ÇáÒãäíÉ", "Feature_Name": "Project Data Date & Reporting Cutoff Governance", "Feature_Name_AR": "ÍæßãÉ ÊÇÑíÎ ŞØÚ ÇáÈíÇäÇÊ (Project Data Date)", "Description_AR": "ÊËÈíÊ ÊÇÑíÎ ãÍÏÏ ááÊŞÑíÑ ÇáÒãäí (Data Date) ÈÍíË íÌãÏ ÇáãÇÖí ßÜ Actual æíÍÓÈ ÇáãÓÊŞÈá ßÜ Forecast.", "PM_Value_AR": "ãÚíÇÑ Ïæáí (Primavera standard) íãäÚ ÊÏÇÎá ÇáÊæÇÑíÎ ÇáãÓÊŞÈáíÉ ãÚ ÇáÊäİíĞ ÇáİÚáí.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí (Reporting Integrity)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate A / A2", "Technical_Evidence": "Data Date logic in App.tsx / Dashboard"},
    {"ID": "SCH-03", "Module": "Schedule & CPM", "Category_AR": "ÇáÌÏæáÉ æÇáãØÇáÈÇÊ ÇáÒãäíÉ", "Feature_Name": "Fragnet Engine & Time Impact Analysis (TIA)", "Feature_Name_AR": "ãÍÑß ÔÈßÇÊ ÇáÊÃÎíÑ æÇáÊÍáíá ÇáÒãäí (TIA & Fragnet)", "Description_AR": "ÍŞä ÃÍÏÇË ÇáÊÃÎíÑ æÇáÊÛííÑÇÊ ßÔÈßÇÊ ãÕÛÑÉ İí ÇáÜ CPM áÇÍÊÓÇÈ ÊÃËíÑåÇ ÇáİæÑí Úáì ÊÇÑíÎ ÇáÊÓáíã.", "PM_Value_AR": "ÅËÈÇÊ ãØÇáÈÇÊ ÇáÊãÏíÏ ÇáÒãäí ÃãÇã ÇáÇÓÊÔÇÑí æÇáãÇáß ØÈŞÇğ áÇÔÊÑÇØÇÊ İíÏíß (FIDIC).", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Claims & LDs Protection)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate 2 / Feat 1", "Technical_Evidence": "calculateTimeImpactAnalysis, Migration 50, 115 tests"},
    {"ID": "SCH-04", "Module": "Schedule & CPM", "Category_AR": "ÇáÌÏæáÉ æÇáãØÇáÈÇÊ ÇáÒãäíÉ", "Feature_Name": "Automatic EOT & Liquidated Damages Exposure", "Feature_Name_AR": "ÍÓÇÈ ÇáÊãÏíÏ ÇáÒãäí ÇáÊáŞÇÆí æãÎÇØÑ ÇáÛÑÇãÇÊ (EOT)", "Description_AR": "ÊÍÏíÏ ÇÓÊÍŞÇŞ ÇáãŞÇæá áÃíÇã ÇáÊãÏíÏ ÇáãÚİÇÉ ãä ÇáÛÑÇãÇÊ (Excusable EOT) æÊÍÏíÏ ãÓÄæáíÉ ÇáÊÃÎíÑ æÛÑÇãÇÊ ÇáÊÃÎíÑ (LDs).", "PM_Value_AR": "ÍãÇíÉ ÇáãŞÇæá ãä ÛÑÇãÇÊ ÇáÊÃÎíÑ ÛíÑ ÇáŞÇäæäíÉ æÊÍÏíÏ ÇáãÓÊÍŞÇÊ ÇáãÇáíÉ Úä ÇáÊãÏíÏ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Contractual Safety)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate 2 / Feat 1", "Technical_Evidence": "EOTSummary, calculation engine, test suite"},
    {"ID": "SCH-05", "Module": "Schedule & CPM", "Category_AR": "ÇáÌÏæáÉ æÇáãØÇáÈÇÊ ÇáÒãäíÉ", "Feature_Name": "3-Way Gantt Overlay (Baseline vs Current vs Forecast)", "Feature_Name_AR": "ãÎØØ ÌÇäÊ ÇáãŞÇÑä ËáÇËí ÇáÃÈÚÇÏ (3-Way Gantt Overlay)", "Description_AR": "ÚÑÖ ÈíÇäí ÊİÇÚáí áßá äÔÇØ íæÖÍ ÎØ ÇáÃÓÇÓ ÇáãÚÊãÏ¡ æÇáÃÏÇÁ ÇáİÚáí¡ æãÓÇÑ ÇáÊæŞÚ ÇáãÓÊŞÈáí ãÚ ÊÍÏíÏ ÇáÃäÔØÉ ÇáÍÑÌÉ ÇáãÊÃÎÑÉ.", "PM_Value_AR": "ÑÄíÉ ÈÕÑíÉ İæÑíÉ ááÇäÍÑÇİÇÊ æãÓÇÚÏÉ ãÏíÑ ÇáãÔÑæÚ İí ÇÊÎÇĞ ŞÑÇÑÇÊ ÖÛØ ÇáÈÑäÇãÌ (Crashing/Fast-tracking).", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Visual Decision)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate 2 / Feat 2", "Technical_Evidence": "calculateGanttOverlay, 116 tests"},
    {"ID": "SCH-06", "Module": "Schedule & CPM", "Category_AR": "ÇáÌÏæáÉ æÇáãØÇáÈÇÊ ÇáÒãäíÉ", "Feature_Name": "Primavera P6 True Round-Trip & XER Reconciliation", "Feature_Name_AR": "ÇáãØÇÈŞÉ æÇáÊßÇãá ÇáßÇãá ãÚ ãáİÇÊ Primavera P6 (XER)", "Description_AR": "ÇÓÊíÑÇÏ æÊÕÏíÑ ãáİÇÊ XER ãÚ İÍÕ ÇáÚáÇŞÇÊ (FS, SS, FF, SF)¡ ÇáÜ Lags¡ ÇáÊŞÇæíã¡ æÇáãØÇÈŞÉ ÇáÂáíÉ ááÊäÇŞÖÇÊ.", "PM_Value_AR": "ÇáÊæÇİŞ ÇáÊÇã ãÚ ÇÓÊÔÇÑíí ÇáãÔÑæÚÇÊ æÅÏÇÑÇÊ ÇáÜ PMO ÇáÊí ÊÔÊÑØ ÇÓÊÎÏÇã Primavera.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí (Interoperability)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 2 / Feat 3", "Technical_Evidence": "XER parser exists, reconciliation engine under test"},

    # 3. Cost & EVM
    {"ID": "CST-01", "Module": "Cost & EVM", "Category_AR": "ÇáÊÍßã İí ÇáÊßÇáíİ æÇáÜ EVM", "Feature_Name": "Comprehensive EVM Core (PV, EV, AC, CV, SV, CPI, SPI)", "Feature_Name_AR": "ãÍÑß ÇáŞíãÉ ÇáãßÊÓÈÉ ÇáÔÇãá (EVM Master)", "Description_AR": "ÇÍÊÓÇÈ ãÄÔÑÇÊ ÇáÃÏÇÁ ÇáÍÓÇÈíÉ æÇáãÇáíÉ ÈÏŞÉ ãÚ ÏÚã ÇáÊÕİíÉ ÍÓÈ ÇáãÔÑæÚ æÍÓÇÈ ÇáÊÍßã.", "PM_Value_AR": "ãÚÑİÉ ÇáÃÏÇÁ ÇáÍŞíŞí ááãÔÑæÚ: åá äÍä ãÊÃÎÑæä¿ æåá ÊÌÇæÒäÇ ÇáãíÒÇäíÉ¿ ÈÃÑŞÇã ŞÇØÚÉ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (PMI Core)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Phase 1A / EVM", "Technical_Evidence": "Dashboard.tsx, EVM calculations"},
    {"ID": "CST-02", "Module": "Cost & EVM", "Category_AR": "ÇáÊÍßã İí ÇáÊßÇáíİ æÇáÜ EVM", "Feature_Name": "5-Factor Cost Variance Breakdown", "Feature_Name_AR": "ÊÍáíá İÑæŞ ÇáÊßáİÉ ÇáÎãÇÓí (Variance Breakdown)", "Description_AR": "Êİßíß ÇäÍÑÇİÇÊ ÇáÊßáİÉ Åáì ÃÓÈÇÈåÇ ÇáÌĞÑíÉ: İÑŞ ÇáßãíÇÊ (Usage)¡ İÑŞ ÇáÃÓÚÇÑ (Rate)¡ İÑŞ ÇáãÒíÌ (Mix)¡ İÑŞ ÇáÅäÊÇÌíÉ (Productivity)¡ æİÑŞ ÇáßİÇÁÉ (Efficiency).", "PM_Value_AR": "ãÚÑİÉ ÇáÓÈÈ ÇáİÚáí ááÎÓÇÑÉ ÈÏŞÉ: åá åí ÒíÇÏÉ ÃÓÚÇÑ ÇáãæÇÏ ãä ÇáÓæŞ Ãã ÖÚİ ÅäÊÇÌíÉ ÇáÚãÇáÉ æÇáãÚÏÇÊ İí ÇáãæŞÚ¿", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Cost Intelligence)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gap C / Complete", "Technical_Evidence": "7caed37, 96fa935, 1dbe8a6, 2ca794c, Dashboard"},
    {"ID": "CST-03", "Module": "Cost & EVM", "Category_AR": "ÇáÊÍßã İí ÇáÊßÇáíİ æÇáÜ EVM", "Feature_Name": "Multi-Method ETC / EAC & TCPI Forecasting", "Feature_Name_AR": "ãÍÑß ÇáÊäÈÄ ãÊÚÏÏ ÇáØÑŞ ááÊßáİÉ (Multi-Method EAC)", "Description_AR": "ÇÍÊÓÇÈ ÇáÊßáİÉ ÇáãÊæŞÚÉ ÚäÏ ÇáÇäÊåÇÁ (EAC) ÈÜ 4 ØÑŞ åäÏÓíÉ ãÊæÇÒíÉ (Budget Rate, CPI, Composite CPI*SPI, Bottom-up) ãÚ ãÄÔÑ ÇáßİÇÁÉ ÇáãØáæÈÉ (TCPI).", "PM_Value_AR": "ÊæŞÚ ÇáÑÈÍ Ãæ ÇáÎÓÇÑÉ ÇáäåÇÆíÉ ááãÔÑæÚ İí Ãí áÍÙÉ æÇÎÊíÇÑ ÇáÓíäÇÑíæ ÇáÃäÓÈ áÙÑæİ ÇáãÔÑæÚ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Executive Foresight)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate 1 / Feat 3", "Technical_Evidence": "calculateMultiMethodEAC, 113 tests"},
    {"ID": "CST-04", "Module": "Cost & EVM", "Category_AR": "ÇáÊÍßã İí ÇáÊßÇáíİ æÇáÜ EVM", "Feature_Name": "Time-Phased Cost Phasing & S-Curve Distribution", "Feature_Name_AR": "ÇáÊæÒíÚ ÇáÒãäí ááÊßÇáíİ æãäÍäíÇÊ ÇáÜ S-Curve", "Description_AR": "ÊæÒíÚ ÇáãíÒÇäíÇÊ æÇáÊßÇáíİ Úáì ÇáÔåæÑ/ÇáİÊÑÇÊ ÈãäÍäíÇÊ ŞíÇÓíÉ (Linear, Bell Curve, Front-Loaded, Back-Loaded, S-Curve) ãÚ ÊÓæíÉ ÇáİÑæŞ ÇáÚÔÑíÉ.", "PM_Value_AR": "ÈäÇÁ ãæÇÒäÇÊ ÔåÑíÉ æÇŞÚíÉ æÇáÊÍßã İí ÇáÊÏİŞÇÊ ÇáäŞÏíÉ ÇáãØáæÈÉ ÔåÑíÇğ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Cash & Budget Phasing)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Gate 1 / Feat 4", "Technical_Evidence": "Migration 49, distributeCostTimePhased, 114 tests"},
    {"ID": "CST-05", "Module": "Cost & EVM", "Category_AR": "ÇáÊÍßã İí ÇáÊßÇáíİ æÇáÜ EVM", "Feature_Name": "Overhead Allocation & CBS Control", "Feature_Name_AR": "ÊæÒíÚ ÇáãÕÇÑíİ ÛíÑ ÇáãÈÇÔÑÉ (Overhead Allocation)", "Description_AR": "ÊÍãíá ÊßÇáíİ ÇáÅÏÇÑÉ æÇáãæŞÚ æÇáãÕÇÑíİ ÇáÚÇãÉ Úáì ÈäæÏ ÇáÃÚãÇá ÈäÓÈ ÚÇÏáÉ æÊÊÈÚ ÇáãíÒÇäíÉ ÇáãÊÇÍÉ.", "PM_Value_AR": "ÇÍÊÓÇÈ ÇáÊßáİÉ ÇáÍŞíŞíÉ ÇáßÇãáÉ ááãÔÑæÚ æÖãÇä ÚÏã ÊÂßá åÇãÔ ÇáÑÈÍ.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí (Real Margins)", "Status": "ãßÊãá æãËÈÊ", "Gate": "bde6b1d / Gap A/B", "Technical_Evidence": "Commit bde6b1d, Control Accounts"},

    # 4. Commercial & Cash Flow
    {"ID": "COM-01", "Module": "Commercial & Cash", "Category_AR": "ÇáÚŞæÏ æÇáÊÌÇÑíÇÊ æÇáÓíæáÉ", "Feature_Name": "Main vs Subcontract Hierarchical Architecture", "Feature_Name_AR": "ÇáãÚãÇÑíÉ ÇáåÑãíÉ ááÚŞÏ ÇáÑÆíÓí æÚŞæÏ ÇáÈÇØä", "Description_AR": "İÕá æãØÇÈŞÉ ÈäæÏ ÇáÚŞÏ ÇáÑÆíÓí ãÚ ÚŞæÏ ãŞÇæáí ÇáÈÇØä¡ ãÚ ÊÌãíÚ ÇáÊßÇáíİ ÊáŞÇÆíÇğ äÍæ ÇáÚŞÏ ÇáÑÆíÓí.", "PM_Value_AR": "ÇáÊÍßã İí ÇáÊÒÇãÇÊ ãŞÇæáí ÇáÈÇØä æÑÈØåÇ ÈäØÇŞ ÇáãÇáß ÇáãÚÊãÏ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Contract Integrity)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Phase 1A", "Technical_Evidence": "Contracts schema, Subcontract roll-up"},
    {"ID": "COM-02", "Module": "Commercial & Cash", "Category_AR": "ÇáÚŞæÏ æÇáÊÌÇÑíÇÊ æÇáÓíæáÉ", "Feature_Name": "3-Way Invoice & Payment Matching", "Feature_Name_AR": "ÇáãØÇÈŞÉ ÇáËáÇËíÉ ááãÓÊÎáÕÇÊ æÇáİæÇÊíÑ (3-Way Matching)", "Description_AR": "ãØÇÈŞÉ ÈäæÏ ÇáİÇÊæÑÉ ãÚ ÃãÑ ÇáÔÑÇÁ (PO) æÓäÏÇÊ ÇÓÊáÇã ÇáãæŞÚ (GRN) æÔåÇÏÇÊ ÇáÅäÌÇÒ ŞÈá ÇÚÊãÇÏ ÇáÕÑİ.", "PM_Value_AR": "ãäÚ ÏİÚ ãáíã æÇÍÏ Ïæä æÌæÏ ÃãÑ ÔÑÇÁ ÑÓãí æÇÓÊáÇã ãæŞÚí ãÚÊãÏ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Audit & Governance)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Commercial Phase", "Technical_Evidence": "Payment certificates, Invoices, Receipts"},
    {"ID": "COM-03", "Module": "Commercial & Cash", "Category_AR": "ÇáÚŞæÏ æÇáÊÌÇÑíÇÊ æÇáÓíæáÉ", "Feature_Name": "Potential Variation Orders (PVO) & Claims Register", "Feature_Name_AR": "ÓÌá ÃæÇãÑ ÇáÊÛííÑ ÇáãÍÊãáÉ æÇáãØÇáÈÇÊ (PVO Register)", "Description_AR": "ÊÓÌíá æÍÕÑ ÇáÃÚãÇá ÇáÅÖÇİíÉ æÊÛííÑÇÊ ÇáäØÇŞ ãäĞ áÍÙÉ ÙåæÑåÇ İí ÇáãæŞÚ æŞÈá ÇÚÊãÇÏåÇ ãä ÇáãÇáß.", "PM_Value_AR": "ÍİÙ ÍŞæŞ ÇáãŞÇæá ÇáãÇáíÉ æÇáÒãäíÉ æãäÚ ÖíÇÚ ÇáãØÇáÈÇÊ ÈÓÈÈ ÇáÊÃÎÑ İí ÊŞÏíãåÇ.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí (Revenue Protection)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 3 / Feat 3", "Technical_Evidence": "Variations module extension"},
    {"ID": "COM-04", "Module": "Commercial & Cash", "Category_AR": "ÇáÚŞæÏ æÇáÊÌÇÑíÇÊ æÇáÓíæáÉ", "Feature_Name": "Subcontractor Back-to-Back Retention & Pay-When-Paid", "Feature_Name_AR": "ÍæßãÉ ãÓÊÎáÕÇÊ ÇáÈÇØä æÇáÏİÚ ÇáãÔÑæØ (Back-to-Back)", "Description_AR": "ÑÈØ ÕÑİ ÏİÚÇÊ ãŞÇæáí ÇáÈÇØä ÈÊÍÕíá ãÓÊÎáÕÇÊ ÇáãÇáß æÇÍÊÌÇÒ ãÈÇáÛ ÖãÇä ÇáÃÚãÇá (Retention).", "PM_Value_AR": "ÍãÇíÉ ÇáÓíæáÉ ÇáäŞÏíÉ ááÔÑßÉ æÊİÇÏí ÇáÚÌÒ ÇáãÇáí ÇáäÇÊÌ Úä ÏİÚ ãÓÊÍŞÇÊ ÇáÈÇØä ŞÈá ŞÈÖ ÇáãÇáß.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí ÌÏÇğ (Cash Survival)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 4 / Feat 1", "Technical_Evidence": "Invoicing & Payment module"},
    {"ID": "COM-05", "Module": "Commercial & Cash", "Category_AR": "ÇáÚŞæÏ æÇáÊÌÇÑíÇÊ æÇáÓíæáÉ", "Feature_Name": "Dynamic Cash Flow Forecasting & Working Capital S-Curve", "Feature_Name_AR": "ÇáÊäÈÄ ÇáÏíäÇãíßí ÈÇáÊÏİŞÇÊ ÇáäŞÏíÉ æÑÃÓ ÇáãÇá ÇáÚÇãá", "Description_AR": "ÑÓã ãäÍäíÇÊ ÇáÓíæáÉ ÇáäŞÏíÉ ÇáãÊæŞÚÉ (ÇáãŞÈæÖÇÊ ÇáãÎØØÉ ãŞÇÈá ÇáãÏİæÚÇÊ) æÇÍÊÓÇÈ ÇáÚÌÒ/ÇáİÇÆÖ ÇáãÇáí ÔåÑíÇğ.", "PM_Value_AR": "ÅäĞÇÑ ÇáÅÏÇÑÉ ãÓÈŞÇğ ÈİÊÑÇÊ ÇáÚÌÒ ÇáäŞÏí áÊÑÊíÈ ÇáÊãæíá ÇáÈäßí ŞÈá ÊÚËÑ ÇáãÔÑæÚ.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí ÌÏÇğ (Financial Liquidity)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 3 / Financial", "Technical_Evidence": "Cash Flow basic exists, dynamic curves pending"},

    # 5. PMO & Governance
    {"ID": "PMO-01", "Module": "PMO & Governance", "Category_AR": "ÇáÑŞÇÈÉ æÇáÅäĞÇÑ ÇáãÈßÑ æÇáÜ PMO", "Feature_Name": "Smart Early Warning System (EWS & Thresholds)", "Feature_Name_AR": "äÙÇã ÇáÅäĞÇÑ ÇáãÈßÑ ÇáĞßí (Early Warning System)", "Description_AR": "ÅØáÇŞ ÊäÈíåÇÊ ĞßíÉ İæÑíÉ ÚäÏ ÊÌÇæÒ ãÄÔÑÇÊ ÇáÎØÑ (ãËá: CPI < 0.90¡ ÊÂßá ÇáÓãÇÍíÉ > 5 ÃíÇã¡ ÚÌÒ ÓíæáÉ).", "PM_Value_AR": "ÇáÊÍæá ãä ÑÏ ÇáİÚá ÇáãÊÃÎÑ ÈÚÏ İæÇÊ ÇáÃæÇä Åáì ÇáÅÏÇÑÉ ÇáÇÓÊÈÇŞíÉ ááãÔÑæÚ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Risk Prevention)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 3 / Feat 1", "Technical_Evidence": "Alerts subsystem exists, smart thresholding pending"},
    {"ID": "PMO-02", "Module": "PMO & Governance", "Category_AR": "ÇáÑŞÇÈÉ æÇáÅäĞÇÑ ÇáãÈßÑ æÇáÜ PMO", "Feature_Name": "Variance Action Register & CAPA Workflow", "Feature_Name_AR": "ÓÌá ÅÌÑÇÁÇÊ ÇáÊÕÍíÍ æÇáÊÍÓíä (Variance Action Register)", "Description_AR": "ÊÍæíá İÑæŞ ÇáÊßáİÉ æÇáæŞÊ ÊáŞÇÆíÇğ Åáì ãåÇã ÊÕÍíÍíÉ (Corrective Actions) ãÓäÏÉ áÃÔÎÇÕ æÊæÇÑíÎ ÅäÌÇÒ ãÚÊãÏÉ.", "PM_Value_AR": "ÅÛáÇŞ ÍáŞÉ ÇáÑŞÇÈÉ æÖãÇä ÚÏã ÈŞÇÁ ÇáÊŞÇÑíÑ ÍÈÑÇğ Úáì æÑŞ Ïæä ÅÌÑÇÁ ÊÕÍíÍí ãíÏÇäí.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí (Accountability & Action)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 3 / Feat 2", "Technical_Evidence": "Work Queue exists, dedicated CAPA pending"},
    {"ID": "PMO-03", "Module": "PMO & Governance", "Category_AR": "ÇáÑŞÇÈÉ æÇáÅäĞÇÑ ÇáãÈßÑ æÇáÜ PMO", "Feature_Name": "Unified Executive Cockpit (C-Level & PMO)", "Feature_Name_AR": "áæÍÉ ÇáŞíÇÏÉ ÇáÊäİíĞíÉ ÇáãæÍÏÉ (Unified Cockpit)", "Description_AR": "ÔÇÔÉ æÇÍÏÉ ÊÌãÚ ÇáäØÇŞ¡ ÇáæŞÊ¡ ÇáÊßáİÉ¡ ÇáÓíæáÉ¡ ÇáãØÇáÈÇÊ¡ æãÓÊæì ÇáÌæÏÉ ÈÖÛØÉ ÒÑ ááÅÏÇÑÉ ÇáÚáíÇ æÇáãÇáß.", "PM_Value_AR": "ÊæİíÑ æŞÊ ÅÚÏÇÏ ÇáÊŞÇÑíÑ æÚÑÖ ÕæÑÉ ãÊßÇãáÉ æãæËæŞÉ Úä ÕÍÉ ÇáãÔÑæÚÇÊ İí ËæÇäò.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Executive Control)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 3 / Feat 4", "Technical_Evidence": "Dashboard exists, unification pending"},
    {"ID": "PMO-04", "Module": "PMO & Governance", "Category_AR": "ÇáÑŞÇÈÉ æÇáÅäĞÇÑ ÇáãÈßÑ æÇáÜ PMO", "Feature_Name": "One-Click Executive Monthly Report Pack (PDF)", "Feature_Name_AR": "ÊæáíÏ ÇáÊŞÑíÑ ÇáÔåÑí ÇáÊäİíĞí ÈÖÛØÉ ÒÑ (Monthly Report Pack)", "Description_AR": "ÊÕÏíÑ ÍÒãÉ ÊŞÇÑíÑ ÔåÑíÉ ÇÍÊÑÇİíÉ ÈÕíÛÉ PDF ÊÍÊæí Úáì S-Curves¡ ãæŞİ ÇáÜ EVM¡ ÇáİÑæŞ¡ æãØÇáÈÇÊ ÇáÜ TIA.", "PM_Value_AR": "ÊæİíÑ ÚÔÑÇÊ ÇáÓÇÚÇÊ ÇáÊí íŞÖíåÇ ÇáãåäÏÓæä ÔåÑíÇğ İí ÊÌåíÒ ÊŞÇÑíÑ Excel æ PowerPoint.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí (Professional Presentation)", "Status": "ŞíÏ ÇáÊØæíÑ ÇáãÎØØ", "Gate": "Gate 4 / Feat 2", "Technical_Evidence": "Reports module extension"},
    {"ID": "PMO-05", "Module": "PMO & Governance", "Category_AR": "ÇáÑŞÇÈÉ æÇáÅäĞÇÑ ÇáãÈßÑ æÇáÜ PMO", "Feature_Name": "Strict Period Locking & Audit Log Trail", "Feature_Name_AR": "Şİá ÇáİÊÑÇÊ ÇáãÍÇÓÈíÉ æÓÌá ÇáÊÏŞíŞ ÇáÕÇÑã (Audit Trail)", "Description_AR": "ÊÌãíÏ ÇáİÊÑÇÊ ÇáÓÇÈŞÉ æãäÚ ÇáÊÚÏíá ÈÃËÑ ÑÌÚí¡ ãÚ ÊÓÌíá ßá ÍÑßÉ æãÓÊÎÏã ææŞÊ ÇáÊÚÏíá (Compliance).", "PM_Value_AR": "ãØÇÈŞÉ ãÚÇííÑ ÇáÍæßãÉ ÇáãÇáíÉ ÇáÏæáíÉ æÇáãÑÇÌÚÉ æãäÚ ÇáÊáÇÚÈ ÈÇáÃÑŞÇã ÇáÊÇÑíÎíÉ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Compliance & Security)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Phase 1A", "Technical_Evidence": "Audit log tables, Reporting-period guards"},

    # 6. Field & UX
    {"ID": "FLD-01", "Module": "Field & Operations", "Category_AR": "ÇáÚãáíÇÊ ÇáãíÏÇäíÉ æÇáÌæÏÉ", "Feature_Name": "Daily Reports & Site Productivity Logs", "Feature_Name_AR": "ÇáÊŞÇÑíÑ ÇáíæãíÉ æÓÌáÇÊ ÅäÊÇÌíÉ ÇáãæŞÚ", "Description_AR": "ÍÕÑ íæãí áÍÖæÑ ÇáÚãÇáÉ¡ ÊÔÛíá ÇáãÚÏÇÊ¡ ÇáØŞÓ¡ æÇáÃÚãÇá ÇáãäİĞÉ æãŞÇÑäÊåÇ ÈãÚÏáÇÊ ÇáÅäÊÇÌíÉ ÇáŞíÇÓíÉ.", "PM_Value_AR": "ÇáÑÈØ ÇáãÈÇÔÑ Èíä ãæŞÚ ÇáÚãá æãßÊÈ ÇáÊÍßã áÖÈØ ÇäÍÑÇİÇÊ ÇáÅäÊÇÌíÉ íæãíÇğ.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí (Field Visibility)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Field Operations", "Technical_Evidence": "Daily Reports, Labor, Equipment tables"},
    {"ID": "FLD-02", "Module": "Field & Operations", "Category_AR": "ÇáÚãáíÇÊ ÇáãíÏÇäíÉ æÇáÌæÏÉ", "Feature_Name": "RFI & Submittals Commercial Impact Linkage", "Feature_Name_AR": "ÑÈØ ÇáÇÓÊİÓÇÑÇÊ (RFI) æÇáÇÚÊãÇÏÇÊ ÈÇáÃËÑ ÇáÒãäí æÇáãÇáí", "Description_AR": "ÑÈØ ÊÃÎÑ ÇÚÊãÇÏ ÇáãÎØØÇÊ Ãæ ÇáÑÏ Úáì ÇÓÊİÓÇÑÇÊ ÇáãæŞÚ (RFI) ÊáŞÇÆíÇğ ÈãÍÑß ÇáÜ TIA áÍÓÇÈ ÃÍÏÇË ÇáÊÃÎíÑ.", "PM_Value_AR": "ÊæËíŞ ãÓÄæáíÉ ÇáÇÓÊÔÇÑí Úä ÊÃÎíÑ ÇÚÊãÇÏ ÇáãæÇÏ æÇáãÎØØÇÊ ßÃÏáÉ ŞÇäæäíÉ ááÊãÏíÏ.", "Priority": "P2 - High", "Business_Impact": "ÚÇáí (Contractual Proof)", "Status": "ãŞÊÑÍ ÇÓÊÑÇÊíÌí", "Gate": "Gate 3 / Field Link", "Technical_Evidence": "RFI / Submittal tables exist, TIA linkage proposed"},
    {"ID": "UX-01", "Module": "User Experience", "Category_AR": "ÊÌÑÈÉ ÇáãÓÊÎÏã æÓåæáÉ ÇáÇÓÊÎÏÇã", "Feature_Name": "Zero-Clutter Role-Based Workspaces", "Feature_Name_AR": "ãÓÇÍÇÊ Úãá ãÎÕÕÉ ÍÓÈ ÇáÏæÑ", "Description_AR": "æÇÌåÇÊ ãÈÓØÉ ÊÙåÑ áßá ãÓÊÎÏã İŞØ ãÇ íÎÕå (ãåäÏÓ ÇáãæŞÚ íÑì WIR æÇáíæãíÇÊ¡ ãÏíÑ ÇáãÔÑæÚ íÑì ÇáãÄÔÑÇÊ æÇáÇÚÊãÇÏÇÊ).", "PM_Value_AR": "ÓåæáÉ ÇáÊÚáã ÇáİæÑíÉ æÇÓÊÎÏÇã ÇáäÙÇã Ïæä ÊÚŞíÏ Ãæ ÊÔÊÊ İí ÇáŞæÇÆã ÇáßËíÑÉ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (User Adoption)", "Status": "ãŞÊÑÍ ÇÓÊÑÇÊíÌí", "Gate": "Gate 4 / UX", "Technical_Evidence": "Users & Permissions structure exists"},
    {"ID": "UX-02", "Module": "User Experience", "Category_AR": "ÊÌÑÈÉ ÇáãÓÊÎÏã æÓåæáÉ ÇáÇÓÊÎÏÇã", "Feature_Name": "Excel-Like Grid Interactions with Formula Arithmetic", "Feature_Name_AR": "ÌÏÇæá ÊİÇÚáíÉ ÊÔÈå Excel ãÚ ÏÚã ÇáãÚÇÏáÇÊ æÇáäÓÎ æÇááÕŞ", "Description_AR": "ÊÚÏíá ÇáÎáÇíÇ ãÈÇÔÑÉ¡ ÇáäÓÎ æÇááÕŞ ÇáÓÑíÚ¡ ÏÚã ÇáİáÇÊÑ ÇáãÊŞÏãÉ¡ æÇáãÚÇÏáÇÊ ÇáÍÓÇÈíÉ ÇáÓÑíÚÉ.", "PM_Value_AR": "ÌÚá ÇäÊŞÇá ÇáãåäÏÓíä ãä Excel ÇáÊŞáíÏí Åáì BuildTrack ÓáÓÇğ æØÈíÚíÇğ æÈÏæä ãŞÇæãÉ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Productivity)", "Status": "ãßÊãá æãËÈÊ", "Gate": "DataTableView Master", "Technical_Evidence": "DataTableView.tsx with multi-cell selection & formulas"},
    {"ID": "UX-03", "Module": "User Experience", "Category_AR": "ÊÌÑÈÉ ÇáãÓÊÎÏã æÓåæáÉ ÇáÇÓÊÎÏÇã", "Feature_Name": "Offline-First Desktop App with Instant Local SQLite", "Feature_Name_AR": "ÊØÈíŞ ÓØÍ ãßÊÈ ÓÑíÚ íÚãá ÈÏæä ÅäÊÑäÊ (Offline-First)", "Description_AR": "ÇáÚãá ÏÇÎá ÇáãæŞÚ æÇáÃäİÇŞ æÇáãäÇØŞ ÇáäÇÆíÉ ÈÏæä ÅäÊÑäÊ ãÚ ÍİÙ ãÍáí İÇÆŞ ÇáÓÑÚÉ ÚÈÑ SQLite ÏÇÎá Tauri.", "PM_Value_AR": "ÇÓÊãÑÇÑíÉ ÇáÚãá İí ÌãíÚ ÇáãæÇŞÚ ÇáÅäÔÇÆíÉ Ïæä ÊæŞİ.", "Priority": "P1 - Critical", "Business_Impact": "ÚÇáí ÌÏÇğ (Field Reliability)", "Status": "ãßÊãá æãËÈÊ", "Gate": "Tauri + Rust Core", "Technical_Evidence": "src-tauri/src/lib.rs (49 Migrations), SqliteRepository"}
]

columns_mapping = {
    "ID": "ßæÏ ÇáãíÒÉ (ID)",
    "Module": "ÇáãÌÇá (Module)",
    "Category_AR": "ÇáÊÕäíİ ÇáÊÔÛíáí",
    "Feature_Name": "ÇÓã ÇáãíÒÉ ÈÇáÅäÌáíÒíÉ",
    "Feature_Name_AR": "ÇÓã ÇáãíÒÉ ÈÇáÚÑÈíÉ",
    "Description_AR": "ÇáæÕİ ÇáåäÏÓí æÇáãÚãÇÑí",
    "PM_Value_AR": "ÇáÃËÑ ÇáÊÔÛíáí æŞíãÉ ÇáãíÒÉ áãÏíÑ ÇáãÔÑæÚ",
    "Priority": "ÇáÃæáæíÉ",
    "Business_Impact": "ÇáÊÃËíÑ ÇáÇÓÊÑÇÊíÌí",
    "Status": "ÇáãæŞİ ÇáÍÇáí",
    "Gate": "ÇáãÑÍáÉ / ÇáÈæÇÈÉ (Gate)",
    "Technical_Evidence": "ÇáÏáíá ÇáÊŞäí æÇáÑÈØ ÇáÈÑãÌí"
}

df = pd.DataFrame(backlog_data).rename(columns=columns_mapping)
output_file = "BuildTrack_Master_Backlog.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Master Backlog", index=False)

wb = openpyxl.load_workbook(output_file)
ws = wb["Master Backlog"]
ws.views.sheetView[0].rightToLeft = True

header_fill = PatternFill(start_color="1A365D", end_color="1A365D", fill_type="solid")
header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
thin_border = Border(left=Side(style='thin', color='CBD5E1'), right=Side(style='thin', color='CBD5E1'), top=Side(style='thin', color='CBD5E1'), bottom=Side(style='thin', color='CBD5E1'))

for col_num in range(1, len(df.columns) + 1):
    cell = ws.cell(row=1, column=col_num)
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell.border = thin_border
ws.row_dimensions[1].height = 30

col_widths = {1: 12, 2: 18, 3: 20, 4: 28, 5: 28, 6: 45, 7: 45, 8: 16, 9: 22, 10: 20, 11: 22, 12: 35}
for col_num, width in col_widths.items():
    ws.column_dimensions[get_column_letter(col_num)].width = width

for row_num in range(2, len(df) + 2):
    ws.row_dimensions[row_num].height = 40
    status_val = str(ws.cell(row=row_num, column=10).value)
    for col_num in range(1, len(df.columns) + 1):
        cell = ws.cell(row=row_num, column=col_num)
        cell.font = Font(name="Segoe UI", size=10)
        cell.border = thin_border
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        if col_num in [1, 2, 8, 9, 10, 11]:
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        if col_num == 10:
            if "ãßÊãá" in status_val:
                cell.fill = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")
                cell.font = Font(name="Segoe UI", size=10, color="065F46", bold=True)
            elif "ŞíÏ ÇáÊØæíÑ" in status_val:
                cell.fill = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
                cell.font = Font(name="Segoe UI", size=10, color="92400E", bold=True)
            elif "ãŞÊÑÍ" in status_val:
                cell.fill = PatternFill(start_color="E0F2FE", end_color="E0F2FE", fill_type="solid")
                cell.font = Font(name="Segoe UI", size=10, color="075985", bold=True)

wb.save(output_file)
print("SUCCESS: BuildTrack_Master_Backlog.xlsx generated in current folder!")
