import { BookOpen, Table2, Upload, Link2, ShieldCheck } from 'lucide-react';
import type { ViewKey } from '@/types';

const guides: { title: string; icon: typeof BookOpen; text: string; steps: string[]; view: ViewKey }[] = [
  { title: 'Work in tables', icon: Table2, text: 'Use the table as a spreadsheet while keeping calculated and governed values protected.', steps: ['Click a cell to select; double-click or F2 to edit an editable cell.', 'Use Shift-click for a range, Ctrl+C / Ctrl+V to copy and paste, and Ctrl+D to fill down.', 'Use Details to inspect one record without leaving the table.'], view: 'boqItems' },
  { title: 'Guided import', icon: Upload, text: 'Choose the project and contract once, download the scoped template, then preview the file before it is saved.', steps: ['Open Guided Data Entry.', 'Select project, contract and BOQ header where required.', 'Download Template, complete only manual fields, Import, review Preview, then confirm.'], view: 'dataEntry' },
  { title: 'Relationships and governance', icon: Link2, text: 'Project, contract, BOQ, schedule and WIR relationships are checked at save time.', steps: ['Create the main contract before the related project records.', 'Create BOQ headers/items before activities and inspection requests.', 'Resolve date, quantity or scope messages before saving.'], view: 'dataQuality' },
  { title: 'Control and reporting', icon: ShieldCheck, text: 'Use grouped views, PMO alerts, the work queue and report packs to review exceptions before they become issues.', steps: ['Group any table by a useful field and click a group to drill down.', 'Review My Work Queue for pending actions and overdue items.', 'Use Executive Report Pack for a print-ready management summary.'], view: 'reportPack' },
];

export function HelpCenter({ onNavigate }: { onNavigate: (view: ViewKey) => void }) {
  return <div className="h-full overflow-y-auto bg-neutral-50 p-4 sm:p-6"><div className="mx-auto max-w-5xl space-y-5"><section className="rounded-2xl border border-primary-200 bg-gradient-to-r from-primary-50 to-white p-6 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-xl bg-primary-100 p-3 text-primary-700"><BookOpen size={25}/></div><div><p className="text-xs font-semibold uppercase tracking-wider text-primary-700">BuildTrack Guide</p><h1 className="mt-1 text-2xl font-bold text-neutral-900">Work confidently with linked project data</h1><p className="mt-1 text-sm text-neutral-600">Short operational guides for entering, reviewing and reporting data safely.</p></div></div></section><div className="grid gap-4 md:grid-cols-2">{guides.map((guide) => { const Icon = guide.icon; return <article key={guide.title} className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-lg bg-primary-50 p-2 text-primary-700"><Icon size={20}/></span><h2 className="font-bold text-neutral-900">{guide.title}</h2></div><p className="mt-3 text-sm leading-6 text-neutral-600">{guide.text}</p><ol className="mt-4 space-y-2 text-sm text-neutral-700">{guide.steps.map((step, index) => <li key={step} className="flex gap-2"><span className="font-semibold text-primary-700">{index + 1}.</span><span>{step}</span></li>)}</ol><button onClick={() => onNavigate(guide.view)} className="mt-5 rounded-lg border border-primary-200 bg-primary-50 px-3 py-2 text-sm font-semibold text-primary-700 hover:bg-primary-100">Open related area</button></article>; })}</div></div></div>;
}
