import { useState } from 'react';
import { Settings2, Save } from 'lucide-react';
import type { ViewKey } from '@/types';

export function PreferencesPanel({ destinations, onSaved }: { destinations: { key: ViewKey; label: string }[]; onSaved: (view: ViewKey) => void }) {
  const [defaultView, setDefaultView] = useState<ViewKey>(() => (localStorage.getItem('buildtrack:default-view') as ViewKey) || 'dashboard');
  const [compactTables, setCompactTables] = useState(() => localStorage.getItem('buildtrack:compact-tables') === 'true');
  const [saved, setSaved] = useState(false);
  function save() { localStorage.setItem('buildtrack:default-view', defaultView); localStorage.setItem('buildtrack:compact-tables', String(compactTables)); setSaved(true); onSaved(defaultView); }
  return <div className="h-full overflow-y-auto bg-neutral-50 p-4 sm:p-6"><div className="mx-auto max-w-3xl space-y-5"><section className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-primary-50 p-3 text-primary-700"><Settings2 size={24}/></div><div><p className="text-xs font-semibold uppercase tracking-wider text-primary-700">Personal preferences</p><h1 className="mt-1 text-2xl font-bold text-neutral-900">Set up your workspace</h1><p className="mt-1 text-sm text-neutral-500">These preferences are stored locally for the current desktop user.</p></div></div><div className="mt-6 space-y-5"><label className="block text-sm font-semibold text-neutral-700">Default page at sign-in<select value={defaultView} onChange={(event) => setDefaultView(event.target.value as ViewKey)} className="mt-2 w-full rounded-lg border border-neutral-300 px-3 py-2 text-sm">{destinations.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-neutral-200 p-4"><input type="checkbox" checked={compactTables} onChange={(event) => setCompactTables(event.target.checked)} className="mt-1 rounded border-neutral-300 text-primary-600"/><span><span className="block text-sm font-semibold text-neutral-800">Compact table rows</span><span className="mt-1 block text-xs leading-5 text-neutral-500">Use denser rows on large BOQ, schedule and transaction registers. It applies after reopening a table.</span></span></label><button onClick={save} className="flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white"><Save size={16}/>Save preferences</button>{saved && <p className="text-sm text-success-700">Preferences saved locally.</p>}</div></section></div></div>;
}
