import { useState } from 'react';
import { Settings2, Save, Moon, Monitor, PanelTop, Focus } from 'lucide-react';
import type { ViewKey } from '@/types';

export type WorkspaceMode = 'professional' | 'compact' | 'focus' | 'dark';

const modes: { key: WorkspaceMode; title: string; detail: string; icon: typeof Monitor }[] = [
  { key: 'professional', title: 'Professional', detail: 'Balanced PMO workspace for everyday management.', icon: Monitor },
  { key: 'compact', title: 'Compact control', detail: 'Denser tables and registers for high-volume data work.', icon: PanelTop },
  { key: 'focus', title: 'Focus canvas', detail: 'Wide working area with navigation hidden by default.', icon: Focus },
  { key: 'dark', title: 'Dark operations', detail: 'Low-glare dark workspace for extended operational sessions.', icon: Moon },
];

export function PreferencesPanel({ destinations, onSaved, mode, onModeSaved }: { destinations: { key: ViewKey; label: string }[]; onSaved: (view: ViewKey) => void; mode: WorkspaceMode; onModeSaved: (mode: WorkspaceMode) => void }) {
  const [defaultView, setDefaultView] = useState<ViewKey>(() => (localStorage.getItem('buildtrack:default-view') as ViewKey) || 'dashboard');
  const [compactTables, setCompactTables] = useState(() => localStorage.getItem('buildtrack:compact-tables') === 'true');
  const [selectedMode, setSelectedMode] = useState<WorkspaceMode>(mode);
  const [saved, setSaved] = useState(false);
  function save() { const compact = selectedMode === 'compact' ? true : compactTables; localStorage.setItem('buildtrack:default-view', defaultView); localStorage.setItem('buildtrack:compact-tables', String(compact)); localStorage.setItem('buildtrack:workspace-mode', selectedMode); setSaved(true); onModeSaved(selectedMode); onSaved(defaultView); }
  return <div className="h-full overflow-y-auto bg-neutral-50 p-4 sm:p-6"><div className="mx-auto max-w-3xl space-y-5"><section className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-primary-50 p-3 text-primary-700"><Settings2 size={24}/></div><div><p className="text-xs font-semibold uppercase tracking-wider text-primary-700">Personal preferences</p><h1 className="mt-1 text-2xl font-bold text-neutral-900">Set up your workspace</h1><p className="mt-1 text-sm text-neutral-500">Choose the visual mode that suits the way you work. Preferences are stored locally.</p></div></div><div className="mt-6 space-y-5"><div><p className="text-sm font-semibold text-neutral-700">Workspace mode</p><div className="mt-2 grid gap-3 sm:grid-cols-2">{modes.map((item) => { const Icon = item.icon; const active = selectedMode === item.key; return <button key={item.key} onClick={() => setSelectedMode(item.key)} className={`rounded-xl border p-4 text-left transition-colors ${active ? 'border-primary-500 bg-primary-50 ring-1 ring-primary-200' : 'border-neutral-200 hover:border-primary-200 hover:bg-neutral-50'}`}><span className={`inline-flex rounded-lg p-2 ${active ? 'bg-primary-600 text-white' : 'bg-neutral-100 text-neutral-600'}`}><Icon size={17}/></span><span className="mt-3 block text-sm font-semibold text-neutral-800">{item.title}</span><span className="mt-1 block text-xs leading-5 text-neutral-500">{item.detail}</span></button>; })}</div></div><label className="block text-sm font-semibold text-neutral-700">Default page at sign-in<select value={defaultView} onChange={(event) => setDefaultView(event.target.value as ViewKey)} className="mt-2 w-full rounded-lg border border-neutral-300 px-3 py-2 text-sm">{destinations.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-neutral-200 p-4"><input type="checkbox" checked={selectedMode === 'compact' || compactTables} disabled={selectedMode === 'compact'} onChange={(event) => setCompactTables(event.target.checked)} className="mt-1 rounded border-neutral-300 text-primary-600"/><span><span className="block text-sm font-semibold text-neutral-800">Compact table rows</span><span className="mt-1 block text-xs leading-5 text-neutral-500">Enabled automatically in Compact control mode. It applies after reopening a table.</span></span></label><button onClick={save} className="flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white"><Save size={16}/>Save preferences</button>{saved && <p className="text-sm text-success-700">Preferences saved locally.</p>}</div></section></div></div>;
}
