import { useMemo, useState } from 'react';
import { FileDown, Printer } from 'lucide-react';

const money = (value: number) => value.toLocaleString(undefined, { style: 'currency', currency: 'SAR', maximumFractionDigits: 0 });

export function ReportPack({ projects, contracts, variations, schedules, costs, wirs, cashFlow }: { projects: Record<string, any>[]; contracts: Record<string, any>[]; variations: Record<string, any>[]; schedules: Record<string, any>[]; costs: Record<string, any>[]; wirs: Record<string, any>[]; cashFlow: Record<string, any>[] }) {
  const [projectId, setProjectId] = useState(projects[0]?.id || 'all');
  const data = useMemo(() => { const ps = projectId === 'all' ? projects : projects.filter((p) => p.id === projectId); const ids = new Set(ps.map((p) => p.id)); const main = contracts.filter((c) => ids.has(c.project_id) && !c.parent_main_contract_id); const contractIds = new Set(main.map((c) => c.id)); const original = main.reduce((s, c) => s + (Number(c.contract_value) || 0), 0); const variation = variations.filter((v) => contractIds.has(v.contract_id) && v.status === 'Approved').reduce((s, v) => s + (Number(v.cost_impact) || 0), 0); const pv = schedules.filter((s) => ids.has(s.project_id) && s.activity).reduce((s, row) => s + (Number(row.planned_value) || 0), 0); const ev = wirs.filter((w) => ids.has(w.project_id) && (w.status === 'Approved' || w.result === 'Pass' || w.result === 'Conditional Pass')).reduce((s, w) => s + (Number(w.item_amount) || 0), 0); const ac = costs.filter((c) => ids.has(c.project_id)).reduce((s, c) => s + (Number(c.actual) || 0), 0); const cash = cashFlow.filter((c) => ids.has(c.project_id)).reduce((s, c) => s + (Number(c.inflow) || 0) - (Number(c.outflow) || 0), 0); return { count: ps.length, original, variation, modified: original + variation, pv, ev, ac, cash, delayed: schedules.filter((s) => ids.has(s.project_id) && s.activity && (s.status === 'Delayed' || (s.end_date && s.end_date < new Date().toISOString().slice(0, 10) && s.status !== 'Completed'))).length }; }, [projectId, projects, contracts, variations, schedules, costs, wirs, cashFlow]);
  const print = () => window.print();
  return <div className="h-full overflow-y-auto bg-neutral-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5"><section className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-primary-700">Report Pack</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-neutral-900">Executive PMO report</h1><p className="mt-1 text-sm text-neutral-500">A print-ready local summary generated from linked commercial, schedule, progress, cost and cash records.</p></div><div className="flex gap-2"><select value={projectId} onChange={(e) => setProjectId(e.target.value)} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm"><option value="all">All projects</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.project_code || p.id} — {p.name}</option>)}</select><button onClick={print} className="flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white"><Printer size={16}/>Print / PDF</button></div></div></section><section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Original contract', data.original], ['Approved variations', data.variation], ['Modified value', data.modified], ['Cash position', data.cash], ['Planned value', data.pv], ['Earned value', data.ev], ['Actual cost', data.ac], ['Delayed activities', data.delayed]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm"><p className="text-xs text-neutral-500">{label}</p><p className="mt-1 text-xl font-bold text-neutral-900">{typeof value === 'number' && String(label) !== 'Delayed activities' ? money(value) : value}</p></div>)}</section><section className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-neutral-900">Management reading</h2><ul className="mt-3 space-y-2 text-sm text-neutral-700"><li>• Portfolio/projects covered: {data.count}</li><li>• Commercial variance: {money(data.variation)}</li><li>• Delivery position: EV {money(data.ev)} against PV {money(data.pv)}</li><li>• Cost position: AC {money(data.ac)}.</li><li>• Schedule exceptions: {data.delayed} delayed activity(s).</li></ul></section></div></div>;
}
