import { useMemo, useState } from 'react';
import { FileText, ImagePlus, Printer, Save, Plus } from 'lucide-react';
import { dataRepository } from '@/data';
import type { ReportTemplate } from '@/types';
import type { LocalDataMutation } from '@/hooks/useData';

const REPORT_FIELDS: Record<string, string[]> = {
  'Client Invoice': ['Invoice Number', 'Project', 'Contract', 'Client', 'Period', 'BOQ Item Code', 'Description', 'Unit', 'Quantity', 'Unit Rate', 'Amount', 'Grand Total', 'Payment Status'],
  'Subcontractor Invoice': ['Invoice Number', 'Project', 'Contract', 'Subcontractor', 'Period', 'BOQ Item Code', 'Description', 'Unit', 'Quantity', 'Unit Rate', 'Amount', 'Grand Total', 'Payment Status'],
  WIR: ['WIR Number', 'Project', 'Contract', 'Contractor', 'BOQ Item Code', 'Description', 'Unit', 'Quantity', 'Unit Price', 'Amount', 'Inspection Date', 'Result', 'Inspector'],
  'Variation Order': ['Variation Number', 'Project', 'Contract', 'Title', 'Description', 'Cost Impact', 'Time Impact', 'Status', 'Approved By', 'Approved Date'],
  'Cost Report': ['Project', 'Contract', 'BOQ Item Code', 'Description', 'Budget', 'Planned Value', 'Actual Cost', 'Earned Value', 'CPI', 'SPI'],
  'Cash Forecast': ['Project', 'Contract', 'Date', 'Category', 'Movement Type', 'Inflow', 'Outflow', 'Net', 'Cumulative Balance', 'Status'],
};

const emptyTemplate = (): Omit<ReportTemplate, 'id' | 'created_at'> => ({
  template_name: '', report_type: 'Client Invoice', title: 'Payment Certificate / Invoice', subtitle: '', logo_data_url: '',
  selected_fields: REPORT_FIELDS['Client Invoice'], footer_text: 'This document was generated by BuildTrack.', accent_color: '#2563eb',
  page_size: 'A4', orientation: 'portrait', show_generated_at: true, show_signatures: false,
});

export function ReportTemplateDesigner({ templates, onMutated }: { templates: ReportTemplate[]; onMutated: (mutation: LocalDataMutation) => void }) {
  const [draft, setDraft] = useState<Omit<ReportTemplate, 'id' | 'created_at'>>(emptyTemplate());
  const [editingId, setEditingId] = useState<string | null>(null);
  const fields = useMemo(() => REPORT_FIELDS[draft.report_type] || [], [draft.report_type]);

  function changeType(report_type: string) {
    setDraft((previous) => ({ ...previous, report_type, selected_fields: REPORT_FIELDS[report_type] || [] }));
  }
  function toggleField(field: string) {
    setDraft((previous) => ({ ...previous, selected_fields: previous.selected_fields.includes(field)
      ? previous.selected_fields.filter((item) => item !== field)
      : [...previous.selected_fields, field] }));
  }
  async function loadLogo(file?: File) {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => setDraft((previous) => ({ ...previous, logo_data_url: String(reader.result || '') }));
    reader.readAsDataURL(file);
  }
  async function save() {
    if (!draft.template_name.trim()) { alert('Template Name is required.'); return; }
    if (draft.selected_fields.length === 0) { alert('Select at least one field.'); return; }
    try {
      if (editingId) {
        const updated = await dataRepository.update<ReportTemplate>('report_templates', editingId, draft);
        onMutated({ type: 'update', row: updated });
      } else {
        const inserted = await dataRepository.insert<ReportTemplate>('report_templates', draft as ReportTemplate);
        onMutated({ type: 'insert', row: inserted });
      }
      setEditingId(null); setDraft(emptyTemplate());
    } catch (error: any) { alert(`Could not save template: ${error.message || 'Unknown error'}`); }
  }
  function preview() {
    const w = window.open('', '_blank', 'width=1000,height=760');
    if (!w) { alert('Allow pop-ups to preview the template.'); return; }
    const esc = (value: unknown) => String(value || '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] || char));
    const cells = draft.selected_fields.map((field) => `<tr><td>${esc(field)}</td><td>{{${esc(field.toLowerCase().replace(/[^a-z0-9]+/g, '_'))}}}</td></tr>`).join('');
    const signatures = draft.show_signatures ? '<div class="signatures"><div>Prepared by</div><div>Reviewed by</div><div>Approved by</div></div>' : '';
    const generated = draft.show_generated_at ? `<span>Generated ${new Date().toLocaleString()}</span>` : '';
    w.document.write(`<!doctype html><html><head><title>${esc(draft.template_name)}</title><style>@page{size:${draft.page_size || 'A4'} ${draft.orientation || 'portrait'};margin:16mm}body{font-family:Arial,sans-serif;margin:40px;color:#1f2937}.head{border-bottom:4px solid ${esc(draft.accent_color)};display:flex;gap:20px;align-items:center;padding-bottom:18px}.logo{max-width:115px;max-height:75px;object-fit:contain}.title{font-size:26px;font-weight:700}.sub{color:#6b7280;margin-top:6px}table{width:100%;border-collapse:collapse;margin-top:28px}td{border:1px solid #d1d5db;padding:10px}td:first-child{width:48%;font-weight:600;background:#f9fafb}footer{margin-top:28px;border-top:1px solid #d1d5db;padding-top:10px;color:#6b7280;font-size:12px;display:flex;justify-content:space-between}.signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;margin-top:70px}.signatures div{border-top:1px solid #64748b;padding-top:8px;text-align:center;font-size:12px}@media print{body{margin:0}}</style></head><body><div class="head">${draft.logo_data_url ? `<img class="logo" src="${draft.logo_data_url}"/>` : ''}<div><div class="title">${esc(draft.title || draft.template_name)}</div><div class="sub">${esc(draft.subtitle)}</div></div></div><table>${cells}</table>${signatures}<footer><span>${esc(draft.footer_text)}</span>${generated}</footer></body></html>`);
    w.document.close();
  }
  return <div className="flex-1 overflow-auto bg-neutral-50 p-6"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[360px_1fr]"><aside className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-neutral-900">Saved Templates</h2><button onClick={() => { setEditingId(null); setDraft(emptyTemplate()); }} className="rounded-lg p-2 text-primary-700 hover:bg-primary-50" title="New template"><Plus size={18}/></button></div>{templates.length === 0 ? <p className="text-sm text-neutral-500">Create the first flexible template.</p> : <div className="space-y-2">{templates.map((template) => <button key={template.id} onClick={() => { const { id, created_at, ...rest } = template; setEditingId(id); setDraft({ ...emptyTemplate(), ...rest, selected_fields: rest.selected_fields || [] }); }} className="w-full rounded-lg border border-neutral-200 p-3 text-left hover:border-primary-300 hover:bg-primary-50"><div className="font-medium text-neutral-800">{template.template_name}</div><div className="mt-1 text-xs text-neutral-500">{template.report_type} · {template.page_size || 'A4'} {template.orientation || 'portrait'}</div></button>)}</div>}</aside><main className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-primary-50 p-3 text-primary-700"><FileText size={22}/></div><div><h1 className="text-xl font-bold text-neutral-900">Flexible Report Designer</h1><p className="text-sm text-neutral-500">Choose content, branding, page setup and sign-off sections. Preview is print/PDF-ready.</p></div></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Template Name<input value={draft.template_name} onChange={(e) => setDraft({ ...draft, template_name: e.target.value })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"/></label><label className="text-sm font-medium">Report Type<select value={draft.report_type} onChange={(e) => changeType(e.target.value)} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2">{Object.keys(REPORT_FIELDS).map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm font-medium">Title<input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"/></label><label className="text-sm font-medium">Subtitle<input value={draft.subtitle} onChange={(e) => setDraft({ ...draft, subtitle: e.target.value })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"/></label><label className="text-sm font-medium">Page Size<select value={draft.page_size} onChange={(e) => setDraft({ ...draft, page_size: e.target.value as 'A4' | 'Letter' })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"><option value="A4">A4</option><option value="Letter">Letter</option></select></label><label className="text-sm font-medium">Orientation<select value={draft.orientation} onChange={(e) => setDraft({ ...draft, orientation: e.target.value as 'portrait' | 'landscape' })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label className="text-sm font-medium">Accent Color<input type="color" value={draft.accent_color} onChange={(e) => setDraft({ ...draft, accent_color: e.target.value })} className="mt-1 h-10 w-full rounded-lg border border-neutral-300"/></label><label className="text-sm font-medium">Logo<ImagePlus size={14} className="ml-1 inline"/><input type="file" accept="image/*" onChange={(e) => void loadLogo(e.target.files?.[0])} className="mt-1 block w-full text-xs"/></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={Boolean(draft.show_generated_at)} onChange={(e) => setDraft({ ...draft, show_generated_at: e.target.checked })}/>Show generation date</label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={Boolean(draft.show_signatures)} onChange={(e) => setDraft({ ...draft, show_signatures: e.target.checked })}/>Add approval signatures</label><label className="text-sm font-medium md:col-span-2">Footer<textarea value={draft.footer_text} onChange={(e) => setDraft({ ...draft, footer_text: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-neutral-300 px-3 py-2"/></label></div><section className="mt-6"><h3 className="font-semibold text-neutral-900">Fields in this report</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{fields.map((field) => <label key={field} className="flex items-center gap-2 rounded-lg border border-neutral-200 p-2 text-sm"><input type="checkbox" checked={draft.selected_fields.includes(field)} onChange={() => toggleField(field)}/>{field}</label>)}</div></section><div className="mt-6 flex gap-2"><button onClick={() => void save()} className="flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 font-medium text-white hover:bg-primary-700"><Save size={16}/>Save Template</button><button onClick={preview} className="flex items-center gap-2 rounded-lg border border-neutral-300 px-4 py-2 font-medium text-neutral-700 hover:bg-neutral-50"><Printer size={16}/>Preview / Print PDF</button></div></main></div></div>;
}
