import { useMemo, useState } from 'react';
import { FileText, ImagePlus, Printer, Save, Plus, Copy } from 'lucide-react';
import { dataRepository } from '@/data';
import { invoke } from '@tauri-apps/api/core';
import type { ReportTemplate, ReportSectionConfig, ReportFieldConfig } from '@/types';
import type { LocalDataMutation } from '@/hooks/useData';
import { REPORT_FIELD_REGISTRY, assertReportFieldAllowed } from '@/data/dataDictionary';

const emptyTemplate = (): Omit<ReportTemplate, 'id' | 'created_at'> => ({
  template_code: 'RPT-' + Math.floor(Math.random() * 10000),
  template_name: '',
  report_type: 'Client Invoice',
  scope: 'Project',
  revision_number: 1,
  status: 'Draft',
  title: 'Payment Certificate / Invoice',
  subtitle: '',
  logo_attachment_id: null,
  sections: [
    { id: 'sec-1', title: 'Main Table', type: 'Table', fields: [] }
  ],
  footer_text: 'This document was generated by BuildTrack.',
  accent_color: '#2563eb',
  page_size: 'A4',
  orientation: 'portrait',
  show_generated_at: true,
  show_signatures: false,
  locale: 'en-US',
  currency: 'USD',
  date_format: 'YYYY-MM-DD',
  owner: 'current_user',
});

export function ReportTemplateDesigner({ templates, onMutated }: { templates: ReportTemplate[]; onMutated: (mutation: LocalDataMutation) => void }) {
  const [draft, setDraft] = useState<Omit<ReportTemplate, 'id' | 'created_at'>>(emptyTemplate());
  const [editingId, setEditingId] = useState<string | null>(null);

  const availableFields = useMemo(() => {
    return REPORT_FIELD_REGISTRY.filter(f => f.allowed_types.includes(draft.report_type));
  }, [draft.report_type]);

  const mainTableSection = draft.sections.find(s => s.type === 'Table') || draft.sections[0];

  function changeType(report_type: string) {
    setDraft((previous) => ({
      ...previous,
      report_type,
      sections: [{ id: 'sec-1', title: 'Main Table', type: 'Table', fields: [] }]
    }));
  }

  function toggleField(field_id: string) {
    const regField = REPORT_FIELD_REGISTRY.find(f => f.field_id === field_id);
    if (!regField) return;

    setDraft(previous => {
      const newSections = [...previous.sections];
      const tableIdx = newSections.findIndex(s => s.type === 'Table');
      if (tableIdx === -1) return previous;

      const table = { ...newSections[tableIdx] };
      const hasField = table.fields.some(f => f.field_id === field_id);
      
      if (hasField) {
        table.fields = table.fields.filter(f => f.field_id !== field_id);
      } else {
        table.fields = [...table.fields, {
          field_id,
          label: regField.label,
          alignment: regField.source === 'calculated' ? 'right' : 'left'
        }];
      }
      
      newSections[tableIdx] = table;
      return { ...previous, sections: newSections };
    });
  }

  async function loadLogo(file?: File) {
    if (!file) return;
    alert("Logo attachment via Blob storage is to be implemented. Using null for now to respect F8 rule: لا يخزن logo base64 ضخمًا في payload");
    setDraft((previous) => ({ ...previous, logo_attachment_id: 'attach-pending' }));
  }

  async function approveTemplate() {
    if (!editingId) return;
    try {
      await invoke('approve_report_template', { request: { id: editingId, approver: draft.owner } });
      const list = await dataRepository.list('report_templates'); const updated = list.find((r: any) => r.id === editingId);
      if (updated) {
        onMutated({ type: 'update', row: updated as ReportTemplate });
        setDraft(updated as ReportTemplate);
      }
    } catch (e: any) { alert(e.message || 'Error approving template'); }
  }

  async function save() {
    if (!draft.template_name.trim()) { alert('Template Name is required.'); return; }
    if (mainTableSection.fields.length === 0) { alert('Select at least one field.'); return; }
    
    // Enforce registry
    for (const sec of draft.sections) {
      for (const f of sec.fields) {
        try {
          assertReportFieldAllowed(f.field_id, draft.report_type);
        } catch (e: any) {
          alert(e.message);
          return;
        }
      }
    }

    try {
      if (editingId) {
        const updated = await dataRepository.update<ReportTemplate>('report_templates', editingId, draft);
        onMutated({ type: 'update', row: updated });
      } else {
        const inserted = await dataRepository.insert<ReportTemplate>('report_templates', draft as ReportTemplate);
        onMutated({ type: 'insert', row: inserted });
      }
      setEditingId(null); setDraft(emptyTemplate());
    } catch (error: any) { alert(`Could not save template: ${error.message || 'Unknown error'}`); }
  }

  function cloneTemplate() {
    setEditingId(null);
    setDraft({ ...draft, template_name: draft.template_name + ' (Copy)', status: 'Draft', revision_number: 1, template_code: 'RPT-' + Math.floor(Math.random() * 10000) });
  }

  function preview() {
    const w = window.open('', '_blank', 'width=1000,height=760');
    if (!w) { alert('Allow pop-ups to preview the template.'); return; }
    const esc = (value: unknown) => String(value || '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] || char));
    
    const cells = mainTableSection.fields.map((field) => `<tr><td>${esc(field.label)}</td><td>{{${esc(field.field_id)}}}</td></tr>`).join('');
    const signatures = draft.show_signatures ? '<div class="signatures"><div>Prepared by</div><div>Reviewed by</div><div>Approved by</div></div>' : '';
    const generated = draft.show_generated_at ? `<span>Generated ${new Date().toLocaleString()}</span>` : '';
    
    w.document.write(`<!doctype html><html><head><title>${esc(draft.template_name)}</title><style>@page{size:${draft.page_size || 'A4'} ${draft.orientation || 'portrait'};margin:16mm}body{font-family:Arial,sans-serif;margin:40px;color:#1f2937}.head{border-bottom:4px solid ${esc(draft.accent_color)};display:flex;gap:20px;align-items:center;padding-bottom:18px}.logo{max-width:115px;max-height:75px;object-fit:contain;background:#e5e7eb;display:flex;align-items:center;justify-content:center;color:#9ca3af}.title{font-size:26px;font-weight:700}.sub{color:#6b7280;margin-top:6px}table{width:100%;border-collapse:collapse;margin-top:28px}td{border:1px solid #d1d5db;padding:10px}td:first-child{width:48%;font-weight:600;background:#f9fafb}footer{margin-top:28px;border-top:1px solid #d1d5db;padding-top:10px;color:#6b7280;font-size:12px;display:flex;justify-content:space-between}.signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;margin-top:70px}.signatures div{border-top:1px solid #64748b;padding-top:8px;text-align:center;font-size:12px}@media print{body{margin:0}}</style></head><body><div class="head">${draft.logo_attachment_id ? `<div class="logo">Logo Area</div>` : ''}<div><div class="title">${esc(draft.title || draft.template_name)}</div><div class="sub">${esc(draft.subtitle)}</div></div></div><table>${cells}</table>${signatures}<footer><span>${esc(draft.footer_text)}</span>${generated}</footer></body></html>`);
    w.document.close();
  }

  return (
    <div className="flex-1 overflow-auto bg-neutral-50 p-6">
      <div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[360px_1fr]">
        <aside className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm">
          <div className="mb-3 flex items-center justify-between">
            <h2 className="font-bold text-neutral-900">Saved Templates</h2>
            <button onClick={() => { setEditingId(null); setDraft(emptyTemplate()); }} className="rounded-lg p-2 text-primary-700 hover:bg-primary-50" title="New template"><Plus size={18}/></button>
          </div>
          {templates.length === 0 ? <p className="text-sm text-neutral-500">Create the first flexible template.</p> : 
          <div className="space-y-2">
            {templates.map((template) => 
              <button key={template.id} onClick={() => { const { id, created_at, ...rest } = template; setEditingId(id); setDraft({ ...emptyTemplate(), ...rest, sections: rest.sections || emptyTemplate().sections }); }} className="w-full rounded-lg border border-neutral-200 p-3 text-left hover:border-primary-300 hover:bg-primary-50">
                <div className="flex items-center justify-between">
                  <div className="font-medium text-neutral-800">{template.template_name}</div>
                  <span className="text-[10px] uppercase font-bold text-neutral-400">{template.status}</span>
                </div>
                <div className="mt-1 text-xs text-neutral-500">{template.report_type} · Rev {template.revision_number}</div>
              </button>
            )}
          </div>}
        </aside>
        <main className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm">
          <div className="mb-5 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="rounded-xl bg-primary-50 p-3 text-primary-700"><FileText size={22}/></div>
              <div>
                <h1 className="text-xl font-bold text-neutral-900">Persistent Report Designer</h1>
                <p className="text-sm text-neutral-500">Choose content, branding, page setup and sign-off sections. Preview is print/PDF-ready.</p>
              </div>
            </div>
            {editingId && (
               <button onClick={cloneTemplate} className="flex items-center gap-2 rounded-lg border border-neutral-300 px-3 py-1.5 text-sm font-medium text-neutral-700 hover:bg-neutral-50">
                 <Copy size={14}/> Clone
               </button>
            )}
          </div>
          
          <div className="grid gap-4 md:grid-cols-2">
            <label className="text-sm font-medium">Template Name
              <input value={draft.template_name} onChange={(e) => setDraft({ ...draft, template_name: e.target.value })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"/>
            </label>
            <label className="text-sm font-medium">Report Type
              <select value={draft.report_type} onChange={(e) => changeType(e.target.value)} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2">
                <option>Client Invoice</option>
                <option>Subcontractor Invoice</option>
                <option>WIR</option>
                <option>Variation Order</option>
                <option>Cost Report</option>
                <option>Cash Forecast</option>
              </select>
            </label>
            <label className="text-sm font-medium">Title
              <input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"/>
            </label>
            <label className="text-sm font-medium">Subtitle
              <input value={draft.subtitle} onChange={(e) => setDraft({ ...draft, subtitle: e.target.value })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2"/>
            </label>
            <label className="text-sm font-medium">Page Size
              <select value={draft.page_size} onChange={(e) => setDraft({ ...draft, page_size: e.target.value as 'A4' | 'Letter' })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2">
                <option value="A4">A4</option><option value="Letter">Letter</option>
              </select>
            </label>
            <label className="text-sm font-medium">Orientation
              <select value={draft.orientation} onChange={(e) => setDraft({ ...draft, orientation: e.target.value as 'portrait' | 'landscape' })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2">
                <option value="portrait">Portrait</option><option value="landscape">Landscape</option>
              </select>
            </label>
            <label className="text-sm font-medium">Status
              <select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as 'Draft' | 'Approved' | 'Superseded' })} className="mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2">
                <option value="Draft">Draft</option><option value="Approved">Approved</option><option value="Superseded">Superseded</option>
              </select>
            </label>
            <label className="text-sm font-medium">Logo
              <ImagePlus size={14} className="ml-1 inline"/>
              <input type="file" accept="image/*" onChange={(e) => void loadLogo(e.target.files?.[0])} className="mt-1 block w-full text-xs"/>
            </label>
            <label className="flex items-center gap-2 text-sm font-medium">
              <input type="checkbox" checked={Boolean(draft.show_generated_at)} onChange={(e) => setDraft({ ...draft, show_generated_at: e.target.checked })}/>Show generation date
            </label>
            <label className="flex items-center gap-2 text-sm font-medium">
              <input type="checkbox" checked={Boolean(draft.show_signatures)} onChange={(e) => setDraft({ ...draft, show_signatures: e.target.checked })}/>Add approval signatures
            </label>
            <label className="text-sm font-medium md:col-span-2">Footer
              <textarea value={draft.footer_text} onChange={(e) => setDraft({ ...draft, footer_text: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-neutral-300 px-3 py-2"/>
            </label>
          </div>
          
          <section className="mt-6 border-t border-neutral-200 pt-6">
            <div className="flex items-center justify-between">
              <h3 className="font-semibold text-neutral-900">Allowed Fields Registry</h3>
              <span className="text-xs text-neutral-500">Only fields governed by data dictionary are allowed.</span>
            </div>
            <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
              {availableFields.map((field) => (
                <label key={field.field_id} className="flex items-center gap-2 rounded-lg border border-neutral-200 p-2 text-sm">
                  <input type="checkbox" checked={mainTableSection.fields.some(f => f.field_id === field.field_id)} onChange={() => toggleField(field.field_id)}/>
                  <div>
                    <div>{field.label}</div>
                    <div className="text-[10px] uppercase text-neutral-400">{field.source}</div>
                  </div>
                </label>
              ))}
            </div>
          </section>
          
          <div className="mt-6 flex gap-2">
            <button onClick={() => void save()} className="flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 font-medium text-white hover:bg-primary-700">
              <Save size={16}/>Save Template
            </button>
            {editingId && draft.status === 'Draft' && (
               <button onClick={approveTemplate} className="flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 font-medium text-white hover:bg-green-700">
                 Approve
               </button>
            )}
            <button onClick={preview} className="flex items-center gap-2 rounded-lg border border-neutral-300 px-4 py-2 font-medium text-neutral-700 hover:bg-neutral-50">
              <Printer size={16}/>Preview / Print PDF
            </button>
          </div>
        </main>
      </div>
    </div>
  );
}
