import { CheckSquare, CircleAlert, Clock3, FileCheck2, ReceiptText } from 'lucide-react';
import type { ViewKey } from '@/types';

type QueueItem = { title: string; detail: string; due?: string; type: string; view: ViewKey; urgency: 'high' | 'medium' | 'low' };

export function WorkQueue({ approvals, tasks, clientInvoices, subInvoices, rfis, quality, dailyReports = [], onNavigate }: {
  approvals: Record<string, any>[];
  tasks: Record<string, any>[];
  clientInvoices: Record<string, any>[];
  subInvoices: Record<string, any>[];
  rfis: Record<string, any>[];
  quality: Record<string, any>[];
  dailyReports?: Record<string, any>[];
  onNavigate: (view: ViewKey) => void;
}) {
  const today = new Date().toISOString().slice(0, 10);
  const queue: QueueItem[] = [
    ...approvals.filter((row) => !['Approved', 'Rejected', 'Cancelled'].includes(row.status)).map((row) => ({ title: row.request_title || row.entity_type || 'Approval required', detail: `${row.entity_type || 'Record'} · ${row.approver || 'No approver assigned'}`, due: row.due_date || row.requested_date, type: 'Approval', view: 'approvals' as ViewKey, urgency: row.due_date && row.due_date < today ? 'high' as const : 'medium' as const })),
    ...tasks.filter((row) => row.status !== 'Completed').map((row) => ({ title: row.task_name || row.title || 'Open task', detail: `${row.owner || 'No owner'} · ${row.status || 'Open'}`, due: row.due_date || row.end_date, type: 'Task', view: 'tasks' as ViewKey, urgency: row.status === 'Delayed' || (row.due_date && row.due_date < today) ? 'high' as const : 'medium' as const })),
    ...clientInvoices.filter((row) => row.due_date && row.due_date < today && row.payment_status !== 'Paid').map((row) => ({ title: `Collect ${row.invoice_number || 'client invoice'}`, detail: `Due ${row.due_date} · ${row.payment_status || 'Unpaid'}`, due: row.due_date, type: 'Collection', view: 'clientInvoiceTracking' as ViewKey, urgency: 'high' as const })),
    ...subInvoices.filter((row) => row.status === 'Approved' && row.payment_status !== 'Paid').map((row) => ({ title: `Pay ${row.invoice_number || 'subcontract invoice'}`, detail: `Approved · ${row.payment_status || 'Unpaid'}`, due: row.due_date, type: 'Liability', view: 'subcontractorInvoiceTracking' as ViewKey, urgency: 'medium' as const })),
    ...rfis.filter((row) => !['Closed', 'Answered'].includes(row.status)).map((row) => ({ title: row.subject || row.title || 'Open RFI', detail: row.status || 'Open', due: row.due_date, type: 'RFI', view: 'rfi' as ViewKey, urgency: row.due_date && row.due_date < today ? 'high' as const : 'low' as const })),
    ...quality.filter((row) => row.status !== 'Closed').map((row) => ({ title: row.title || row.description || 'Open quality item', detail: row.status || 'Open', due: row.due_date, type: 'Quality', view: 'quality' as ViewKey, urgency: row.severity === 'Critical' || row.severity === 'High' ? 'high' as const : 'low' as const })),
    ...dailyReports.filter((row) => row.status !== 'Reviewed').map((row) => ({ title: `Review daily report ${row.report_number || ''}`, detail: `${row.report_date || 'No date'} · ${row.status || 'Draft'}`, due: row.report_date, type: 'Site report', view: 'dailyReports' as ViewKey, urgency: row.report_date && row.report_date < today ? 'medium' as const : 'low' as const })),
  ].sort((a, b) => (a.urgency === 'high' ? -1 : b.urgency === 'high' ? 1 : String(a.due || '9999').localeCompare(String(b.due || '9999'))));
  const tone = { high: 'border-error-200 bg-error-50 text-error-800', medium: 'border-warning-200 bg-warning-50 text-warning-800', low: 'border-neutral-200 bg-white text-neutral-800' };
  const high = queue.filter((item) => item.urgency === 'high').length;
  return <div className="h-full overflow-y-auto bg-neutral-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5"><section className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-xl bg-primary-50 p-3 text-primary-700"><CheckSquare size={24}/></div><div><p className="text-xs font-semibold uppercase tracking-wider text-primary-700">My Work Queue</p><h1 className="mt-1 text-2xl font-bold text-neutral-900">Approvals, follow-ups and overdue controls</h1><p className="mt-1 text-sm text-neutral-500">A single operational queue generated from local approvals, tasks, invoices and field registers.</p></div></div></section><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[[CircleAlert, 'Urgent', high, 'text-error-700'], [FileCheck2, 'Approvals', approvals.filter((row) => !['Approved', 'Rejected', 'Cancelled'].includes(row.status)).length, 'text-primary-700'], [Clock3, 'Open tasks', tasks.filter((row) => row.status !== 'Completed').length, 'text-warning-700'], [ReceiptText, 'Open items', queue.length, 'text-neutral-800']].map(([Icon, label, value, color]: any) => <div key={label} className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm"><Icon size={18} className={color}/><p className="mt-2 text-xs text-neutral-500">{label}</p><p className={`text-2xl font-bold ${color}`}>{value}</p></div>)}</div><section className="space-y-2">{queue.map((item, index) => <button key={`${item.type}-${item.title}-${index}`} onClick={() => onNavigate(item.view)} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left transition hover:shadow-sm ${tone[item.urgency]}`}><span className="rounded-full bg-white/70 px-2 py-1 text-xs font-semibold">{item.type}</span><span className="min-w-0 flex-1"><span className="block font-semibold">{item.title}</span><span className="mt-1 block text-sm opacity-90">{item.detail}</span></span><span className="text-xs font-medium">{item.due ? `Due ${item.due}` : 'No due date'} →</span></button>)}{!queue.length && <div className="rounded-xl border border-success-200 bg-success-50 p-10 text-center text-success-700"><p className="font-semibold">No open work item found</p><p className="mt-1 text-sm">The local registers contain no pending approval, task, overdue collection, RFI or quality item.</p></div>}</section></div></div>;
}
