//! Governed commercial workflow: SOV revisions, cost-change approval and
//! payment-certificate cash posting are committed as one SQLite transaction.
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sqlx::{sqlite::SqliteConnectOptions, Row, Sqlite, SqlitePool, Transaction};
use std::path::Path;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApprovalRequest { pub operation_id: String, pub source_id: String, pub actor: String, pub approved_at: String }
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CertificateSettlementRequest { pub operation_id: String, pub certificate_id: String, pub actor: String, pub paid_at: String }
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReversalRequest { pub operation_id: String, pub source_table: String, pub source_id: String, pub actor: String, pub reason: String }
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Result { pub operation_id: String, pub status: String }

#[derive(Clone)]
struct Scope { project_id:String, contract_id:Option<String>, boq_header_id:Option<String>, boq_item_id:Option<String>, parent_main_project_id:Option<String>, parent_main_contract_id:Option<String> }
fn stamp()->String { use std::time::{SystemTime,UNIX_EPOCH}; format!("{}Z",SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis()) }
fn n(v:&Value,k:&str)->f64 {v.get(k).and_then(Value::as_f64).unwrap_or(0.0)}
fn s(v:&Value,k:&str)->String {v.get(k).and_then(Value::as_str).unwrap_or_default().to_string()}
fn money(v:f64)->f64 {(v*100.0).round()/100.0}
async fn db(path:&Path)->std::result::Result<SqlitePool,String>{SqlitePool::connect_with(SqliteConnectOptions::new().filename(path).create_if_missing(true).foreign_keys(true)).await.map_err(|e|e.to_string())}
async fn scope_doc(tx:&mut Transaction<'_,Sqlite>,table:&str,id:&str)->std::result::Result<(Scope,Value),String>{
 let q=format!("SELECT project_id,contract_id,boq_header_id,boq_item_id,parent_main_project_id,parent_main_contract_id,payload FROM {table} WHERE id=?");
 let r=sqlx::query(&q).bind(id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?.ok_or("Commercial document was not found.")?;
 let scope=Scope{project_id:r.try_get("project_id").map_err(|e|e.to_string())?,contract_id:r.try_get("contract_id").map_err(|e|e.to_string())?,boq_header_id:r.try_get("boq_header_id").map_err(|e|e.to_string())?,boq_item_id:r.try_get("boq_item_id").map_err(|e|e.to_string())?,parent_main_project_id:r.try_get("parent_main_project_id").map_err(|e|e.to_string())?,parent_main_contract_id:r.try_get("parent_main_contract_id").map_err(|e|e.to_string())?};
 Ok((scope,serde_json::from_str(&r.try_get::<String,_>("payload").map_err(|e|e.to_string())?).map_err(|e|e.to_string())?))
}
async fn guard(tx:&mut Transaction<'_,Sqlite>,id:&str,on:bool)->std::result::Result<(),String>{if on{sqlx::query("INSERT INTO commercial_mutation_guard(operation_id,created_at) VALUES (?,?)").bind(id).bind(stamp()).execute(&mut **tx).await}else{sqlx::query("DELETE FROM commercial_mutation_guard WHERE operation_id=?").bind(id).execute(&mut **tx).await}.map_err(|e|e.to_string())?;Ok(())}
async fn put(tx:&mut Transaction<'_,Sqlite>,table:&str,id:&str,v:&Value)->std::result::Result<(),String>{let g=format!("internal:{table}:{id}");guard(tx,&g,true).await?;let q=format!("UPDATE {table} SET payload=? WHERE id=?");sqlx::query(&q).bind(v.to_string()).bind(id).execute(&mut **tx).await.map_err(|e|e.to_string())?;guard(tx,&g,false).await}
async fn post(tx:&mut Transaction<'_,Sqlite>,id:&str,table:&str,source:&str,kind:&str,actor:&str,day:&str,reason:&str,snapshot:&Value)->std::result::Result<(),String>{sqlx::query("INSERT INTO commercial_workflow_postings(id,created_at,source_table,source_id,posting_type,status,actor,effective_date,reason,snapshot_json) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id).bind(stamp()).bind(table).bind(source).bind(kind).bind("Posted").bind(actor).bind(day).bind(reason).bind(snapshot.to_string()).execute(&mut **tx).await.map_err(|e|e.to_string())?;Ok(())}
async fn cash(tx:&mut Transaction<'_,Sqlite>,scope:&Scope,source:&str,day:&str,number:&str,kind:&str,status:&str,amount:f64,client:bool)->std::result::Result<(),String>{
 sqlx::query("DELETE FROM cash_flow WHERE json_extract(payload,'$.source_type') LIKE 'payment_certificate_%' AND json_extract(payload,'$.source_id')=?").bind(source).execute(&mut **tx).await.map_err(|e|e.to_string())?;
 if amount.abs()<0.000001{return Ok(())};let id=format!("payment_certificate_{}:{}",kind.to_lowercase(),source);let payload=json!({"id":id,"date":day,"description":format!("Payment certificate {kind}: {number}"),"category":if client{"Client Receipt"}else{"Subcontractor Payment"},"inflow":if client{money(amount)}else{0.0},"outflow":if client{0.0}else{money(amount)},"net":if client{money(amount)}else{money(-amount)},"cumulative_balance":0,"movement_type":kind,"status":status,"source_type":format!("payment_certificate_{}",kind.to_lowercase()),"source_id":source});
 sqlx::query("INSERT INTO cash_flow(id,created_at,project_id,contract_id,boq_header_id,boq_item_id,parent_main_project_id,parent_main_contract_id,payload) VALUES (?,?,?,?,?,?,?,?,?)").bind(id).bind(stamp()).bind(&scope.project_id).bind(&scope.contract_id).bind(&scope.boq_header_id).bind(&scope.boq_item_id).bind(&scope.parent_main_project_id).bind(&scope.parent_main_contract_id).bind(payload.to_string()).execute(&mut **tx).await.map_err(|e|e.to_string())?;Ok(())
}
async fn synchronize_invoice_tracking(tx:&mut Transaction<'_,Sqlite>,certificate:&Value,payment_date:Option<&str>,reversed:bool)->std::result::Result<(),String>{
 let tracking_id=s(certificate,"invoice_tracking_id"); if tracking_id.is_empty(){return Ok(())}; let client=s(certificate,"certificate_type")=="Client";
 let tracking_table=if client{"client_invoice_tracking"}else{"subcontractor_invoice_tracking"}; let invoice_table=if client{"client_invoices"}else{"subcontractor_invoices"};
 let q=format!("SELECT project_id,contract_id,payload FROM {tracking_table} WHERE id=?"); let row=sqlx::query(&q).bind(&tracking_id).fetch_optional(&mut **tx).await.map_err(|e|e.to_string())?.ok_or("Selected invoice register row no longer exists.")?;
 let project:String=row.try_get("project_id").map_err(|e|e.to_string())?;let contract:Option<String>=row.try_get("contract_id").map_err(|e|e.to_string())?;if project!=s(certificate,"project_id")||contract.as_deref()!=Some(s(certificate,"contract_id").as_str()){return Err("Certificate and invoice register must share the same project and contract.".into())};let tracking:Value=serde_json::from_str(&row.try_get::<String,_>("payload").map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let number=s(&tracking,"invoice_number");if number.is_empty(){return Err("Selected invoice register has no invoice number.".into())};let(status,payment_status)=if reversed{("Generated","Unpaid")}else if payment_date.is_some(){("Approved","Paid")}else{("Approved","Unpaid")};
 let tracking_update=format!("UPDATE {tracking_table} SET payload=json_set(payload,'$.status',?,'$.payment_status',?,'$.payment_date',?) WHERE id=?");sqlx::query(&tracking_update).bind(status).bind(payment_status).bind(payment_date).bind(&tracking_id).execute(&mut **tx).await.map_err(|e|e.to_string())?;let invoice_update=format!("UPDATE {invoice_table} SET payload=json_set(payload,'$.status',?,'$.payment_status',?,'$.payment_date',?) WHERE json_extract(payload,'$.invoice_number')=?");sqlx::query(&invoice_update).bind(status).bind(payment_status).bind(payment_date).bind(&number).execute(&mut **tx).await.map_err(|e|e.to_string())?;Ok(())
}
async fn recompute_sov(tx:&mut Transaction<'_,Sqlite>,sov_id:&str)->std::result::Result<(),String>{
 let (_,mut sov)=scope_doc(tx,"contract_sov_lines",sov_id).await?;
 let changes:f64=sqlx::query_scalar("SELECT CAST(COALESCE(sum(CAST(json_extract(payload,'$.amount') AS REAL)),0) AS REAL) FROM cost_changes WHERE contract_sov_line_id=? AND json_extract(payload,'$.status')='Approved'").bind(sov_id).fetch_one(&mut **tx).await.map_err(|e|e.to_string())?;
 let revised=money(n(&sov,"original_budget")+changes); let actual=n(&sov,"actual_cost");
 // The persisted value is a governed baseline only.  The UI/reporting control
 // engine combines it with live PO/GRN facts; an explicit override is never
 // allowed to lower the revised SOV budget during a cost-change approval.
 let forecast=revised.max(n(&sov,"forecast_override"));
 let o=sov.as_object_mut().ok_or("Invalid SOV payload.")?;
 o.insert("approved_cost_change_value".into(),json!(money(changes)));o.insert("revised_budget".into(),json!(revised));o.insert("forecast_at_completion".into(),json!(forecast));o.insert("cost_to_complete".into(),json!(money((forecast-actual).max(0.0))));
 put(tx,"contract_sov_lines",sov_id,&sov).await
}
pub async fn approve_cost_change(path:&Path,r:ApprovalRequest)->std::result::Result<Result,String>{if r.operation_id.trim().is_empty()||r.actor.trim().is_empty()||r.approved_at.trim().is_empty(){return Err("Cost-change approval requires operation ID, actor and date.".into())}let mut tx=db(path).await?.begin().await.map_err(|e|e.to_string())?;guard(&mut tx,&r.operation_id,true).await?;let outcome=async{let(change_scope,mut v)=scope_doc(&mut tx,"cost_changes",&r.source_id).await?;if s(&v,"status")!="Submitted"{return Err("Only a submitted cost change can be approved.".into())}let sov=s(&v,"contract_sov_line_id");if sov.is_empty(){return Err("Cost-change approval requires exactly one Contract SOV line.".into())}let row:Option<(String,String)>=sqlx::query_as("SELECT project_id,contract_id FROM contract_sov_lines WHERE id=?").bind(&sov).fetch_optional(&mut *tx).await.map_err(|e|e.to_string())?;let (project,contract)=row.ok_or("Selected Contract SOV line was not found.")?;if project!=change_scope.project_id||change_scope.contract_id.as_deref()!=Some(contract.as_str()){return Err("Cost change and selected SOV line must share the same project and contract.".into())}let o=v.as_object_mut().ok_or("Invalid cost-change payload.")?;o.insert("status".into(),json!("Approved"));o.insert("approved_by".into(),json!(r.actor));o.insert("approved_date".into(),json!(r.approved_at));put(&mut tx,"cost_changes",&r.source_id,&v).await?;recompute_sov(&mut tx,&sov).await?;post(&mut tx,&r.operation_id,"cost_changes",&r.source_id,"CostChangeApproval",&r.actor,&r.approved_at,"Approved cost change",&v).await}.await;match outcome{Ok(())=>{guard(&mut tx,&r.operation_id,false).await?;tx.commit().await.map_err(|e|e.to_string())?;Ok(Result{operation_id:r.operation_id,status:"Posted".into()})},Err(e)=>{tx.rollback().await.map_err(|x|x.to_string())?;Err(e)}}}
pub async fn approve_payment_certificate(path:&Path,r:ApprovalRequest)->std::result::Result<Result,String>{if r.operation_id.trim().is_empty()||r.actor.trim().is_empty()||r.approved_at.trim().is_empty(){return Err("Certificate approval requires operation ID, actor and date.".into())}let mut tx=db(path).await?.begin().await.map_err(|e|e.to_string())?;guard(&mut tx,&r.operation_id,true).await?;let outcome=async{let(scope,mut v)=scope_doc(&mut tx,"payment_certificates",&r.source_id).await?;if s(&v,"status")!="Submitted"{return Err("Only a submitted payment certificate can be approved.".into())}if !matches!(s(&v,"certificate_type").as_str(),"Client"|"Subcontractor"){return Err("Certificate type must be Client or Subcontractor.".into())}if n(&v,"gross_certified_value")<=0.0{return Err("Payment certificate gross value must be greater than zero.".into())}let gross=n(&v,"gross_certified_value");let retention=money(gross*n(&v,"retention_rate")/100.0);let taxable=money(gross-retention-n(&v,"advance_recovery")-n(&v,"deductions"));if taxable < -0.000001{return Err("Retention, advance recovery and deductions cannot exceed gross certified value.".into())}let tax=money(taxable.max(0.0)*n(&v,"tax_rate")/100.0);let net=money(taxable+tax);let day=if s(&v,"certificate_date").is_empty(){r.approved_at.clone()}else{s(&v,"certificate_date")};let client=s(&v,"certificate_type")=="Client";let o=v.as_object_mut().ok_or("Invalid certificate payload.")?;for(k,value)in[("retention_amount",retention),("taxable_amount",taxable),("tax_amount",tax),("net_certified_value",net)]{o.insert(k.into(),json!(value));}o.insert("status".into(),json!("Approved"));o.insert("approved_by".into(),json!(r.actor));o.insert("approved_date".into(),json!(r.approved_at));put(&mut tx,"payment_certificates",&r.source_id,&v).await?;synchronize_invoice_tracking(&mut tx,&v,None,false).await?;cash(&mut tx,&scope,&r.source_id,&day,&s(&v,"certificate_number"),"Forecast","Open",net,client).await?;post(&mut tx,&r.operation_id,"payment_certificates",&r.source_id,"PaymentCertificateApproval",&r.actor,&r.approved_at,"Approved payment certificate",&v).await}.await;match outcome{Ok(())=>{guard(&mut tx,&r.operation_id,false).await?;tx.commit().await.map_err(|e|e.to_string())?;Ok(Result{operation_id:r.operation_id,status:"Posted".into()})},Err(e)=>{tx.rollback().await.map_err(|x|x.to_string())?;Err(e)}}}
pub async fn settle_payment_certificate(path:&Path,r:CertificateSettlementRequest)->std::result::Result<Result,String>{if r.operation_id.trim().is_empty()||r.actor.trim().is_empty()||r.paid_at.trim().is_empty(){return Err("Certificate settlement requires operation ID, actor and payment date.".into())}let mut tx=db(path).await?.begin().await.map_err(|e|e.to_string())?;guard(&mut tx,&r.operation_id,true).await?;let outcome=async{let(scope,mut v)=scope_doc(&mut tx,"payment_certificates",&r.certificate_id).await?;if s(&v,"status")!="Approved"{return Err("Only an approved payment certificate can be settled.".into())}let net=n(&v,"net_certified_value");if net<=0.0{return Err("Approved certificate has no governed net value.".into())}let client=s(&v,"certificate_type")=="Client";let o=v.as_object_mut().ok_or("Invalid certificate payload.")?;o.insert("status".into(),json!("Paid"));o.insert("payment_date".into(),json!(r.paid_at));o.insert("paid_by".into(),json!(r.actor));put(&mut tx,"payment_certificates",&r.certificate_id,&v).await?;synchronize_invoice_tracking(&mut tx,&v,Some(&r.paid_at),false).await?;cash(&mut tx,&scope,&r.certificate_id,&r.paid_at,&s(&v,"certificate_number"),"Actual","Settled",net,client).await?;post(&mut tx,&r.operation_id,"payment_certificates",&r.certificate_id,"PaymentCertificateSettlement",&r.actor,&r.paid_at,"Settled payment certificate",&v).await}.await;match outcome{Ok(())=>{guard(&mut tx,&r.operation_id,false).await?;tx.commit().await.map_err(|e|e.to_string())?;Ok(Result{operation_id:r.operation_id,status:"Posted".into()})},Err(e)=>{tx.rollback().await.map_err(|x|x.to_string())?;Err(e)}}}
pub async fn reverse_commercial_posting(path:&Path,r:ReversalRequest)->std::result::Result<Result,String>{if !matches!(r.source_table.as_str(),"cost_changes"|"payment_certificates")||r.operation_id.trim().is_empty()||r.actor.trim().is_empty()||r.reason.trim().is_empty(){return Err("Commercial reversal requires source, operation ID, actor and reason.".into())}let mut tx=db(path).await?.begin().await.map_err(|e|e.to_string())?;guard(&mut tx,&r.operation_id,true).await?;let outcome=async{let(scope,mut v)=scope_doc(&mut tx,&r.source_table,&r.source_id).await?;if !matches!(s(&v,"status").as_str(),"Approved"|"Paid"){return Err("Only an approved or paid commercial document can be reversed.".into())}let snapshot=v.clone();let sov=s(&v,"contract_sov_line_id");let o=v.as_object_mut().ok_or("Invalid commercial payload.")?;o.insert("status".into(),json!("Reversed"));o.insert("reversed_by".into(),json!(r.actor));o.insert("reversal_reason".into(),json!(r.reason));put(&mut tx,&r.source_table,&r.source_id,&v).await?;if r.source_table=="payment_certificates"{synchronize_invoice_tracking(&mut tx,&v,None,true).await?;cash(&mut tx,&scope,&r.source_id,"",&s(&v,"certificate_number"),"Reversed","Reversed",0.0,false).await?;}else{recompute_sov(&mut tx,&sov).await?;}post(&mut tx,&r.operation_id,&r.source_table,&r.source_id,"CommercialReversal",&r.actor,&stamp(),&r.reason,&snapshot).await}.await;match outcome{Ok(())=>{guard(&mut tx,&r.operation_id,false).await?;tx.commit().await.map_err(|e|e.to_string())?;Ok(Result{operation_id:r.operation_id,status:"Posted".into()})},Err(e)=>{tx.rollback().await.map_err(|x|x.to_string())?;Err(e)}}}

#[cfg(test)]
mod tests {
 use super::*;
 async fn setup(path:&Path){let p=db(path).await.unwrap();for q in [
  "CREATE TABLE contract_sov_lines(id TEXT PRIMARY KEY,created_at TEXT,project_id TEXT,contract_id TEXT,boq_header_id TEXT,boq_item_id TEXT,parent_main_project_id TEXT,parent_main_contract_id TEXT,payload TEXT)",
  "CREATE TABLE cost_changes(id TEXT PRIMARY KEY,created_at TEXT,project_id TEXT,contract_id TEXT,boq_header_id TEXT,boq_item_id TEXT,parent_main_project_id TEXT,parent_main_contract_id TEXT,contract_sov_line_id TEXT,payload TEXT)",
  "CREATE TABLE payment_certificates(id TEXT PRIMARY KEY,created_at TEXT,project_id TEXT,contract_id TEXT,boq_header_id TEXT,boq_item_id TEXT,parent_main_project_id TEXT,parent_main_contract_id TEXT,payload TEXT)",
  "CREATE TABLE client_invoice_tracking(id TEXT PRIMARY KEY,created_at TEXT,project_id TEXT,contract_id TEXT,boq_header_id TEXT,boq_item_id TEXT,parent_main_project_id TEXT,parent_main_contract_id TEXT,payload TEXT)",
  "CREATE TABLE client_invoices(id TEXT PRIMARY KEY,created_at TEXT,project_id TEXT,contract_id TEXT,boq_header_id TEXT,boq_item_id TEXT,parent_main_project_id TEXT,parent_main_contract_id TEXT,payload TEXT)",
  "CREATE TABLE cash_flow(id TEXT PRIMARY KEY,created_at TEXT,project_id TEXT,contract_id TEXT,boq_header_id TEXT,boq_item_id TEXT,parent_main_project_id TEXT,parent_main_contract_id TEXT,payload TEXT)",
  "CREATE TABLE commercial_mutation_guard(operation_id TEXT PRIMARY KEY,created_at TEXT)",
  "CREATE TABLE commercial_workflow_postings(id TEXT PRIMARY KEY,created_at TEXT,source_table TEXT,source_id TEXT,posting_type TEXT,status TEXT,actor TEXT,effective_date TEXT,reason TEXT,snapshot_json TEXT,UNIQUE(source_table,source_id,posting_type))",
  "CREATE TRIGGER cc_guard BEFORE UPDATE ON cost_changes WHEN json_extract(NEW.payload,'$.status') IN ('Approved','Reversed') AND NOT EXISTS(SELECT 1 FROM commercial_mutation_guard) BEGIN SELECT RAISE(ABORT,'governed commercial required'); END",
  "CREATE TRIGGER cert_guard BEFORE UPDATE ON payment_certificates WHEN json_extract(NEW.payload,'$.status') IN ('Approved','Paid','Reversed') AND NOT EXISTS(SELECT 1 FROM commercial_mutation_guard) BEGIN SELECT RAISE(ABORT,'governed commercial required'); END"
 ]{sqlx::query(q).execute(&p).await.unwrap();}
  sqlx::query("INSERT INTO contract_sov_lines VALUES('s','t','p','c',NULL,NULL,NULL,NULL,?)").bind(json!({"original_budget":1000,"status":"Active"}).to_string()).execute(&p).await.unwrap();
  sqlx::query("INSERT INTO cost_changes VALUES('cc','t','p','c',NULL,NULL,NULL,NULL,'s',?)").bind(json!({"contract_sov_line_id":"s","amount":200,"status":"Submitted","effective_date":"2026-08-01"}).to_string()).execute(&p).await.unwrap();
  sqlx::query("INSERT INTO client_invoice_tracking VALUES('track','t','p','c',NULL,NULL,NULL,NULL,?)").bind(json!({"invoice_number":"INV-1","status":"Generated","payment_status":"Unpaid"}).to_string()).execute(&p).await.unwrap();sqlx::query("INSERT INTO client_invoices VALUES('inv','t','p','c',NULL,NULL,NULL,NULL,?)").bind(json!({"invoice_number":"INV-1","status":"Generated","payment_status":"Unpaid"}).to_string()).execute(&p).await.unwrap();
  sqlx::query("INSERT INTO payment_certificates VALUES('pc','t','p','c',NULL,NULL,NULL,NULL,?)").bind(json!({"project_id":"p","contract_id":"c","invoice_tracking_id":"track","certificate_number":"PC-1","certificate_type":"Client","certificate_date":"2026-08-02","gross_certified_value":1000,"retention_rate":10,"advance_recovery":50,"deductions":25,"tax_rate":15,"status":"Submitted"}).to_string()).execute(&p).await.unwrap();p.close().await;}
 #[tokio::test]
 async fn commercial_workflow_posts_sov_net_cash_and_reverses_without_duplicates(){let path=std::env::temp_dir().join(format!("buildtrack-commercial-{}.db",std::process::id()));let _=std::fs::remove_file(&path);setup(&path).await;
  approve_cost_change(&path,ApprovalRequest{operation_id:"a1".into(),source_id:"cc".into(),actor:"tester".into(),approved_at:"2026-08-01".into()}).await.unwrap();
  approve_payment_certificate(&path,ApprovalRequest{operation_id:"a2".into(),source_id:"pc".into(),actor:"tester".into(),approved_at:"2026-08-02".into()}).await.unwrap();let p=db(&path).await.unwrap();let revised:f64=sqlx::query_scalar("SELECT CAST(json_extract(payload,'$.revised_budget') AS REAL) FROM contract_sov_lines WHERE id='s'").fetch_one(&p).await.unwrap();let forecast:f64=sqlx::query_scalar("SELECT CAST(json_extract(payload,'$.inflow') AS REAL) FROM cash_flow WHERE json_extract(payload,'$.source_id')='pc'").fetch_one(&p).await.unwrap();assert_eq!((revised,forecast),(1200.0,948.75));p.close().await;
  settle_payment_certificate(&path,CertificateSettlementRequest{operation_id:"s1".into(),certificate_id:"pc".into(),actor:"tester".into(),paid_at:"2026-08-03".into()}).await.unwrap();let p=db(&path).await.unwrap();let rows:i64=sqlx::query_scalar("SELECT count(*) FROM cash_flow WHERE json_extract(payload,'$.source_id')='pc'").fetch_one(&p).await.unwrap();let status:String=sqlx::query_scalar("SELECT json_extract(payload,'$.status') FROM payment_certificates WHERE id='pc'").fetch_one(&p).await.unwrap();let paid:String=sqlx::query_scalar("SELECT json_extract(payload,'$.payment_status') FROM client_invoice_tracking WHERE id='track'").fetch_one(&p).await.unwrap();assert_eq!((rows,status,paid),(1,"Paid".into(),"Paid".into()));p.close().await;
  reverse_commercial_posting(&path,ReversalRequest{operation_id:"r1".into(),source_table:"payment_certificates".into(),source_id:"pc".into(),actor:"tester".into(),reason:"correction".into()}).await.unwrap();let p=db(&path).await.unwrap();let remaining:i64=sqlx::query_scalar("SELECT count(*) FROM cash_flow WHERE json_extract(payload,'$.source_id')='pc'").fetch_one(&p).await.unwrap();let postings:i64=sqlx::query_scalar("SELECT count(*) FROM commercial_workflow_postings").fetch_one(&p).await.unwrap();let reset:String=sqlx::query_scalar("SELECT json_extract(payload,'$.payment_status') FROM client_invoice_tracking WHERE id='track'").fetch_one(&p).await.unwrap();assert_eq!((remaining,postings,reset),(0,4,"Unpaid".into()));p.close().await;let _=std::fs::remove_file(&path);}
 #[tokio::test]
 async fn sql_guard_rejects_direct_commercial_approval(){let path=std::env::temp_dir().join(format!("buildtrack-commercial-guard-{}.db",std::process::id()));let _=std::fs::remove_file(&path);setup(&path).await;let p=db(&path).await.unwrap();let result=sqlx::query("UPDATE payment_certificates SET payload=? WHERE id='pc'").bind(json!({"status":"Approved"}).to_string()).execute(&p).await;assert!(result.is_err());p.close().await;let _=std::fs::remove_file(&path);}
}
